// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: failsafe_command.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_failsafe_5fcommand_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_failsafe_5fcommand_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_failsafe_5fcommand_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_failsafe_5fcommand_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_failsafe_5fcommand_2eproto;
namespace sftwin {
namespace failsafe {
class FailsafeCommandProto;
class FailsafeCommandProtoDefaultTypeInternal;
extern FailsafeCommandProtoDefaultTypeInternal _FailsafeCommandProto_default_instance_;
}  // namespace failsafe
}  // namespace sftwin
PROTOBUF_NAMESPACE_OPEN
template<> ::sftwin::failsafe::FailsafeCommandProto* Arena::CreateMaybeMessage<::sftwin::failsafe::FailsafeCommandProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sftwin {
namespace failsafe {

// ===================================================================

class FailsafeCommandProto PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sftwin.failsafe.FailsafeCommandProto) */ {
 public:
  inline FailsafeCommandProto() : FailsafeCommandProto(nullptr) {};
  virtual ~FailsafeCommandProto();

  FailsafeCommandProto(const FailsafeCommandProto& from);
  FailsafeCommandProto(FailsafeCommandProto&& from) noexcept
    : FailsafeCommandProto() {
    *this = ::std::move(from);
  }

  inline FailsafeCommandProto& operator=(const FailsafeCommandProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline FailsafeCommandProto& operator=(FailsafeCommandProto&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FailsafeCommandProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FailsafeCommandProto* internal_default_instance() {
    return reinterpret_cast<const FailsafeCommandProto*>(
               &_FailsafeCommandProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FailsafeCommandProto& a, FailsafeCommandProto& b) {
    a.Swap(&b);
  }
  inline void Swap(FailsafeCommandProto* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FailsafeCommandProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FailsafeCommandProto* New() const final {
    return CreateMaybeMessage<FailsafeCommandProto>(nullptr);
  }

  FailsafeCommandProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FailsafeCommandProto>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FailsafeCommandProto& from);
  void MergeFrom(const FailsafeCommandProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FailsafeCommandProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sftwin.failsafe.FailsafeCommandProto";
  }
  protected:
  explicit FailsafeCommandProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_failsafe_5fcommand_2eproto);
    return ::descriptor_table_failsafe_5fcommand_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCommandIdFieldNumber = 1,
    kTargetDeviceIdFieldNumber = 2,
    kActionTypeFieldNumber = 3,
    kTriggerReasonFieldNumber = 4,
    kIssuedTimestampNsFieldNumber = 5,
    kProcessedTimestampNsFieldNumber = 6,
  };
  // string command_id = 1;
  void clear_command_id();
  const std::string& command_id() const;
  void set_command_id(const std::string& value);
  void set_command_id(std::string&& value);
  void set_command_id(const char* value);
  void set_command_id(const char* value, size_t size);
  std::string* mutable_command_id();
  std::string* release_command_id();
  void set_allocated_command_id(std::string* command_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_command_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_command_id(
      std::string* command_id);
  private:
  const std::string& _internal_command_id() const;
  void _internal_set_command_id(const std::string& value);
  std::string* _internal_mutable_command_id();
  public:

  // string target_device_id = 2;
  void clear_target_device_id();
  const std::string& target_device_id() const;
  void set_target_device_id(const std::string& value);
  void set_target_device_id(std::string&& value);
  void set_target_device_id(const char* value);
  void set_target_device_id(const char* value, size_t size);
  std::string* mutable_target_device_id();
  std::string* release_target_device_id();
  void set_allocated_target_device_id(std::string* target_device_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_target_device_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_target_device_id(
      std::string* target_device_id);
  private:
  const std::string& _internal_target_device_id() const;
  void _internal_set_target_device_id(const std::string& value);
  std::string* _internal_mutable_target_device_id();
  public:

  // string action_type = 3;
  void clear_action_type();
  const std::string& action_type() const;
  void set_action_type(const std::string& value);
  void set_action_type(std::string&& value);
  void set_action_type(const char* value);
  void set_action_type(const char* value, size_t size);
  std::string* mutable_action_type();
  std::string* release_action_type();
  void set_allocated_action_type(std::string* action_type);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_action_type();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_action_type(
      std::string* action_type);
  private:
  const std::string& _internal_action_type() const;
  void _internal_set_action_type(const std::string& value);
  std::string* _internal_mutable_action_type();
  public:

  // string trigger_reason = 4;
  void clear_trigger_reason();
  const std::string& trigger_reason() const;
  void set_trigger_reason(const std::string& value);
  void set_trigger_reason(std::string&& value);
  void set_trigger_reason(const char* value);
  void set_trigger_reason(const char* value, size_t size);
  std::string* mutable_trigger_reason();
  std::string* release_trigger_reason();
  void set_allocated_trigger_reason(std::string* trigger_reason);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_trigger_reason();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_trigger_reason(
      std::string* trigger_reason);
  private:
  const std::string& _internal_trigger_reason() const;
  void _internal_set_trigger_reason(const std::string& value);
  std::string* _internal_mutable_trigger_reason();
  public:

  // int64 issued_timestamp_ns = 5;
  void clear_issued_timestamp_ns();
  ::PROTOBUF_NAMESPACE_ID::int64 issued_timestamp_ns() const;
  void set_issued_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_issued_timestamp_ns() const;
  void _internal_set_issued_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 processed_timestamp_ns = 6;
  void clear_processed_timestamp_ns();
  ::PROTOBUF_NAMESPACE_ID::int64 processed_timestamp_ns() const;
  void set_processed_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_processed_timestamp_ns() const;
  void _internal_set_processed_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:sftwin.failsafe.FailsafeCommandProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr command_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr target_device_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr action_type_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr trigger_reason_;
  ::PROTOBUF_NAMESPACE_ID::int64 issued_timestamp_ns_;
  ::PROTOBUF_NAMESPACE_ID::int64 processed_timestamp_ns_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_failsafe_5fcommand_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FailsafeCommandProto

// string command_id = 1;
inline void FailsafeCommandProto::clear_command_id() {
  command_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& FailsafeCommandProto::command_id() const {
  // @@protoc_insertion_point(field_get:sftwin.failsafe.FailsafeCommandProto.command_id)
  return _internal_command_id();
}
inline void FailsafeCommandProto::set_command_id(const std::string& value) {
  _internal_set_command_id(value);
  // @@protoc_insertion_point(field_set:sftwin.failsafe.FailsafeCommandProto.command_id)
}
inline std::string* FailsafeCommandProto::mutable_command_id() {
  // @@protoc_insertion_point(field_mutable:sftwin.failsafe.FailsafeCommandProto.command_id)
  return _internal_mutable_command_id();
}
inline const std::string& FailsafeCommandProto::_internal_command_id() const {
  return command_id_.Get();
}
inline void FailsafeCommandProto::_internal_set_command_id(const std::string& value) {

  command_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void FailsafeCommandProto::set_command_id(std::string&& value) {

  command_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:sftwin.failsafe.FailsafeCommandProto.command_id)
}
inline void FailsafeCommandProto::set_command_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);

  command_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:sftwin.failsafe.FailsafeCommandProto.command_id)
}
inline void FailsafeCommandProto::set_command_id(const char* value,
    size_t size) {

  command_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:sftwin.failsafe.FailsafeCommandProto.command_id)
}
inline std::string* FailsafeCommandProto::_internal_mutable_command_id() {

  return command_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* FailsafeCommandProto::release_command_id() {
  // @@protoc_insertion_point(field_release:sftwin.failsafe.FailsafeCommandProto.command_id)
  return command_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FailsafeCommandProto::set_allocated_command_id(std::string* command_id) {
  if (command_id != nullptr) {

  } else {

  }
  command_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), command_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:sftwin.failsafe.FailsafeCommandProto.command_id)
}
inline std::string* FailsafeCommandProto::unsafe_arena_release_command_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:sftwin.failsafe.FailsafeCommandProto.command_id)
  GOOGLE_DCHECK(GetArena() != nullptr);

  return command_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void FailsafeCommandProto::unsafe_arena_set_allocated_command_id(
    std::string* command_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (command_id != nullptr) {

  } else {

  }
  command_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      command_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sftwin.failsafe.FailsafeCommandProto.command_id)
}

// string target_device_id = 2;
inline void FailsafeCommandProto::clear_target_device_id() {
  target_device_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& FailsafeCommandProto::target_device_id() const {
  // @@protoc_insertion_point(field_get:sftwin.failsafe.FailsafeCommandProto.target_device_id)
  return _internal_target_device_id();
}
inline void FailsafeCommandProto::set_target_device_id(const std::string& value) {
  _internal_set_target_device_id(value);
  // @@protoc_insertion_point(field_set:sftwin.failsafe.FailsafeCommandProto.target_device_id)
}
inline std::string* FailsafeCommandProto::mutable_target_device_id() {
  // @@protoc_insertion_point(field_mutable:sftwin.failsafe.FailsafeCommandProto.target_device_id)
  return _internal_mutable_target_device_id();
}
inline const std::string& FailsafeCommandProto::_internal_target_device_id() const {
  return target_device_id_.Get();
}
inline void FailsafeCommandProto::_internal_set_target_device_id(const std::string& value) {

  target_device_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void FailsafeCommandProto::set_target_device_id(std::string&& value) {

  target_device_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:sftwin.failsafe.FailsafeCommandProto.target_device_id)
}
inline void FailsafeCommandProto::set_target_device_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);

  target_device_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:sftwin.failsafe.FailsafeCommandProto.target_device_id)
}
inline void FailsafeCommandProto::set_target_device_id(const char* value,
    size_t size) {

  target_device_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:sftwin.failsafe.FailsafeCommandProto.target_device_id)
}
inline std::string* FailsafeCommandProto::_internal_mutable_target_device_id() {

  return target_device_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* FailsafeCommandProto::release_target_device_id() {
  // @@protoc_insertion_point(field_release:sftwin.failsafe.FailsafeCommandProto.target_device_id)
  return target_device_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FailsafeCommandProto::set_allocated_target_device_id(std::string* target_device_id) {
  if (target_device_id != nullptr) {

  } else {

  }
  target_device_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), target_device_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:sftwin.failsafe.FailsafeCommandProto.target_device_id)
}
inline std::string* FailsafeCommandProto::unsafe_arena_release_target_device_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:sftwin.failsafe.FailsafeCommandProto.target_device_id)
  GOOGLE_DCHECK(GetArena() != nullptr);

  return target_device_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void FailsafeCommandProto::unsafe_arena_set_allocated_target_device_id(
    std::string* target_device_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (target_device_id != nullptr) {

  } else {

  }
  target_device_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      target_device_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sftwin.failsafe.FailsafeCommandProto.target_device_id)
}

// string action_type = 3;
inline void FailsafeCommandProto::clear_action_type() {
  action_type_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& FailsafeCommandProto::action_type() const {
  // @@protoc_insertion_point(field_get:sftwin.failsafe.FailsafeCommandProto.action_type)
  return _internal_action_type();
}
inline void FailsafeCommandProto::set_action_type(const std::string& value) {
  _internal_set_action_type(value);
  // @@protoc_insertion_point(field_set:sftwin.failsafe.FailsafeCommandProto.action_type)
}
inline std::string* FailsafeCommandProto::mutable_action_type() {
  // @@protoc_insertion_point(field_mutable:sftwin.failsafe.FailsafeCommandProto.action_type)
  return _internal_mutable_action_type();
}
inline const std::string& FailsafeCommandProto::_internal_action_type() const {
  return action_type_.Get();
}
inline void FailsafeCommandProto::_internal_set_action_type(const std::string& value) {

  action_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void FailsafeCommandProto::set_action_type(std::string&& value) {

  action_type_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:sftwin.failsafe.FailsafeCommandProto.action_type)
}
inline void FailsafeCommandProto::set_action_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);

  action_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:sftwin.failsafe.FailsafeCommandProto.action_type)
}
inline void FailsafeCommandProto::set_action_type(const char* value,
    size_t size) {

  action_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:sftwin.failsafe.FailsafeCommandProto.action_type)
}
inline std::string* FailsafeCommandProto::_internal_mutable_action_type() {

  return action_type_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* FailsafeCommandProto::release_action_type() {
  // @@protoc_insertion_point(field_release:sftwin.failsafe.FailsafeCommandProto.action_type)
  return action_type_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FailsafeCommandProto::set_allocated_action_type(std::string* action_type) {
  if (action_type != nullptr) {

  } else {

  }
  action_type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), action_type,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:sftwin.failsafe.FailsafeCommandProto.action_type)
}
inline std::string* FailsafeCommandProto::unsafe_arena_release_action_type() {
  // @@protoc_insertion_point(field_unsafe_arena_release:sftwin.failsafe.FailsafeCommandProto.action_type)
  GOOGLE_DCHECK(GetArena() != nullptr);

  return action_type_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void FailsafeCommandProto::unsafe_arena_set_allocated_action_type(
    std::string* action_type) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (action_type != nullptr) {

  } else {

  }
  action_type_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      action_type, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sftwin.failsafe.FailsafeCommandProto.action_type)
}

// string trigger_reason = 4;
inline void FailsafeCommandProto::clear_trigger_reason() {
  trigger_reason_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& FailsafeCommandProto::trigger_reason() const {
  // @@protoc_insertion_point(field_get:sftwin.failsafe.FailsafeCommandProto.trigger_reason)
  return _internal_trigger_reason();
}
inline void FailsafeCommandProto::set_trigger_reason(const std::string& value) {
  _internal_set_trigger_reason(value);
  // @@protoc_insertion_point(field_set:sftwin.failsafe.FailsafeCommandProto.trigger_reason)
}
inline std::string* FailsafeCommandProto::mutable_trigger_reason() {
  // @@protoc_insertion_point(field_mutable:sftwin.failsafe.FailsafeCommandProto.trigger_reason)
  return _internal_mutable_trigger_reason();
}
inline const std::string& FailsafeCommandProto::_internal_trigger_reason() const {
  return trigger_reason_.Get();
}
inline void FailsafeCommandProto::_internal_set_trigger_reason(const std::string& value) {

  trigger_reason_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void FailsafeCommandProto::set_trigger_reason(std::string&& value) {

  trigger_reason_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:sftwin.failsafe.FailsafeCommandProto.trigger_reason)
}
inline void FailsafeCommandProto::set_trigger_reason(const char* value) {
  GOOGLE_DCHECK(value != nullptr);

  trigger_reason_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:sftwin.failsafe.FailsafeCommandProto.trigger_reason)
}
inline void FailsafeCommandProto::set_trigger_reason(const char* value,
    size_t size) {

  trigger_reason_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:sftwin.failsafe.FailsafeCommandProto.trigger_reason)
}
inline std::string* FailsafeCommandProto::_internal_mutable_trigger_reason() {

  return trigger_reason_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* FailsafeCommandProto::release_trigger_reason() {
  // @@protoc_insertion_point(field_release:sftwin.failsafe.FailsafeCommandProto.trigger_reason)
  return trigger_reason_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FailsafeCommandProto::set_allocated_trigger_reason(std::string* trigger_reason) {
  if (trigger_reason != nullptr) {

  } else {

  }
  trigger_reason_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), trigger_reason,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:sftwin.failsafe.FailsafeCommandProto.trigger_reason)
}
inline std::string* FailsafeCommandProto::unsafe_arena_release_trigger_reason() {
  // @@protoc_insertion_point(field_unsafe_arena_release:sftwin.failsafe.FailsafeCommandProto.trigger_reason)
  GOOGLE_DCHECK(GetArena() != nullptr);

  return trigger_reason_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void FailsafeCommandProto::unsafe_arena_set_allocated_trigger_reason(
    std::string* trigger_reason) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (trigger_reason != nullptr) {

  } else {

  }
  trigger_reason_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      trigger_reason, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sftwin.failsafe.FailsafeCommandProto.trigger_reason)
}

// int64 issued_timestamp_ns = 5;
inline void FailsafeCommandProto::clear_issued_timestamp_ns() {
  issued_timestamp_ns_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 FailsafeCommandProto::_internal_issued_timestamp_ns() const {
  return issued_timestamp_ns_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 FailsafeCommandProto::issued_timestamp_ns() const {
  // @@protoc_insertion_point(field_get:sftwin.failsafe.FailsafeCommandProto.issued_timestamp_ns)
  return _internal_issued_timestamp_ns();
}
inline void FailsafeCommandProto::_internal_set_issued_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value) {

  issued_timestamp_ns_ = value;
}
inline void FailsafeCommandProto::set_issued_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_issued_timestamp_ns(value);
  // @@protoc_insertion_point(field_set:sftwin.failsafe.FailsafeCommandProto.issued_timestamp_ns)
}

// int64 processed_timestamp_ns = 6;
inline void FailsafeCommandProto::clear_processed_timestamp_ns() {
  processed_timestamp_ns_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 FailsafeCommandProto::_internal_processed_timestamp_ns() const {
  return processed_timestamp_ns_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 FailsafeCommandProto::processed_timestamp_ns() const {
  // @@protoc_insertion_point(field_get:sftwin.failsafe.FailsafeCommandProto.processed_timestamp_ns)
  return _internal_processed_timestamp_ns();
}
inline void FailsafeCommandProto::_internal_set_processed_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value) {

  processed_timestamp_ns_ = value;
}
inline void FailsafeCommandProto::set_processed_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_processed_timestamp_ns(value);
  // @@protoc_insertion_point(field_set:sftwin.failsafe.FailsafeCommandProto.processed_timestamp_ns)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace failsafe
}  // namespace sftwin

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_failsafe_5fcommand_2eproto
