// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: failsafe_command.proto

#include "failsafe_command.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace sftwin {
namespace failsafe {
class FailsafeCommandProtoDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<FailsafeCommandProto> _instance;
} _FailsafeCommandProto_default_instance_;
}  // namespace failsafe
}  // namespace sftwin
static void InitDefaultsscc_info_FailsafeCommandProto_failsafe_5fcommand_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::sftwin::failsafe::_FailsafeCommandProto_default_instance_;
    new (ptr) ::sftwin::failsafe::FailsafeCommandProto();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::sftwin::failsafe::FailsafeCommandProto::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_FailsafeCommandProto_failsafe_5fcommand_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_FailsafeCommandProto_failsafe_5fcommand_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_failsafe_5fcommand_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_failsafe_5fcommand_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_failsafe_5fcommand_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_failsafe_5fcommand_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sftwin::failsafe::FailsafeCommandProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::sftwin::failsafe::FailsafeCommandProto, command_id_),
  PROTOBUF_FIELD_OFFSET(::sftwin::failsafe::FailsafeCommandProto, target_device_id_),
  PROTOBUF_FIELD_OFFSET(::sftwin::failsafe::FailsafeCommandProto, action_type_),
  PROTOBUF_FIELD_OFFSET(::sftwin::failsafe::FailsafeCommandProto, trigger_reason_),
  PROTOBUF_FIELD_OFFSET(::sftwin::failsafe::FailsafeCommandProto, issued_timestamp_ns_),
  PROTOBUF_FIELD_OFFSET(::sftwin::failsafe::FailsafeCommandProto, processed_timestamp_ns_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::sftwin::failsafe::FailsafeCommandProto)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::sftwin::failsafe::_FailsafeCommandProto_default_instance_),
};

const char descriptor_table_protodef_failsafe_5fcommand_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\026failsafe_command.proto\022\017sftwin.failsaf"
  "e\"\256\001\n\024FailsafeCommandProto\022\022\n\ncommand_id"
  "\030\001 \001(\t\022\030\n\020target_device_id\030\002 \001(\t\022\023\n\013acti"
  "on_type\030\003 \001(\t\022\026\n\016trigger_reason\030\004 \001(\t\022\033\n"
  "\023issued_timestamp_ns\030\005 \001(\003\022\036\n\026processed_"
  "timestamp_ns\030\006 \001(\003b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_failsafe_5fcommand_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_failsafe_5fcommand_2eproto_sccs[1] = {
  &scc_info_FailsafeCommandProto_failsafe_5fcommand_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_failsafe_5fcommand_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_failsafe_5fcommand_2eproto = {
  false, false, descriptor_table_protodef_failsafe_5fcommand_2eproto, "failsafe_command.proto", 226,
  &descriptor_table_failsafe_5fcommand_2eproto_once, descriptor_table_failsafe_5fcommand_2eproto_sccs, descriptor_table_failsafe_5fcommand_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_failsafe_5fcommand_2eproto::offsets,
  file_level_metadata_failsafe_5fcommand_2eproto, 1, file_level_enum_descriptors_failsafe_5fcommand_2eproto, file_level_service_descriptors_failsafe_5fcommand_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_failsafe_5fcommand_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_failsafe_5fcommand_2eproto)), true);
namespace sftwin {
namespace failsafe {

// ===================================================================

void FailsafeCommandProto::InitAsDefaultInstance() {
}
class FailsafeCommandProto::_Internal {
 public:
};

FailsafeCommandProto::FailsafeCommandProto(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:sftwin.failsafe.FailsafeCommandProto)
}
FailsafeCommandProto::FailsafeCommandProto(const FailsafeCommandProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  command_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_command_id().empty()) {
    command_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_command_id(),
      GetArena());
  }
  target_device_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_target_device_id().empty()) {
    target_device_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_target_device_id(),
      GetArena());
  }
  action_type_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_action_type().empty()) {
    action_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_action_type(),
      GetArena());
  }
  trigger_reason_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_trigger_reason().empty()) {
    trigger_reason_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_trigger_reason(),
      GetArena());
  }
  ::memcpy(&issued_timestamp_ns_, &from.issued_timestamp_ns_,
    static_cast<size_t>(reinterpret_cast<char*>(&processed_timestamp_ns_) -
    reinterpret_cast<char*>(&issued_timestamp_ns_)) + sizeof(processed_timestamp_ns_));
  // @@protoc_insertion_point(copy_constructor:sftwin.failsafe.FailsafeCommandProto)
}

void FailsafeCommandProto::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_FailsafeCommandProto_failsafe_5fcommand_2eproto.base);
  command_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  target_device_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  action_type_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  trigger_reason_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&issued_timestamp_ns_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&processed_timestamp_ns_) -
      reinterpret_cast<char*>(&issued_timestamp_ns_)) + sizeof(processed_timestamp_ns_));
}

FailsafeCommandProto::~FailsafeCommandProto() {
  // @@protoc_insertion_point(destructor:sftwin.failsafe.FailsafeCommandProto)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void FailsafeCommandProto::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  command_id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  target_device_id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  action_type_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  trigger_reason_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void FailsafeCommandProto::ArenaDtor(void* object) {
  FailsafeCommandProto* _this = reinterpret_cast< FailsafeCommandProto* >(object);
  (void)_this;
}
void FailsafeCommandProto::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void FailsafeCommandProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const FailsafeCommandProto& FailsafeCommandProto::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_FailsafeCommandProto_failsafe_5fcommand_2eproto.base);
  return *internal_default_instance();
}


void FailsafeCommandProto::Clear() {
// @@protoc_insertion_point(message_clear_start:sftwin.failsafe.FailsafeCommandProto)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  command_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  target_device_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  action_type_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  trigger_reason_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&issued_timestamp_ns_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&processed_timestamp_ns_) -
      reinterpret_cast<char*>(&issued_timestamp_ns_)) + sizeof(processed_timestamp_ns_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FailsafeCommandProto::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string command_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_command_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "sftwin.failsafe.FailsafeCommandProto.command_id"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string target_device_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_target_device_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "sftwin.failsafe.FailsafeCommandProto.target_device_id"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string action_type = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_action_type();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "sftwin.failsafe.FailsafeCommandProto.action_type"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string trigger_reason = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_trigger_reason();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "sftwin.failsafe.FailsafeCommandProto.trigger_reason"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 issued_timestamp_ns = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          issued_timestamp_ns_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 processed_timestamp_ns = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          processed_timestamp_ns_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* FailsafeCommandProto::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sftwin.failsafe.FailsafeCommandProto)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string command_id = 1;
  if (this->command_id().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_command_id().data(), static_cast<int>(this->_internal_command_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sftwin.failsafe.FailsafeCommandProto.command_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_command_id(), target);
  }

  // string target_device_id = 2;
  if (this->target_device_id().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_target_device_id().data(), static_cast<int>(this->_internal_target_device_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sftwin.failsafe.FailsafeCommandProto.target_device_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_target_device_id(), target);
  }

  // string action_type = 3;
  if (this->action_type().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_action_type().data(), static_cast<int>(this->_internal_action_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sftwin.failsafe.FailsafeCommandProto.action_type");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_action_type(), target);
  }

  // string trigger_reason = 4;
  if (this->trigger_reason().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_trigger_reason().data(), static_cast<int>(this->_internal_trigger_reason().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sftwin.failsafe.FailsafeCommandProto.trigger_reason");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_trigger_reason(), target);
  }

  // int64 issued_timestamp_ns = 5;
  if (this->issued_timestamp_ns() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(5, this->_internal_issued_timestamp_ns(), target);
  }

  // int64 processed_timestamp_ns = 6;
  if (this->processed_timestamp_ns() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(6, this->_internal_processed_timestamp_ns(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sftwin.failsafe.FailsafeCommandProto)
  return target;
}

size_t FailsafeCommandProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sftwin.failsafe.FailsafeCommandProto)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string command_id = 1;
  if (this->command_id().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_command_id());
  }

  // string target_device_id = 2;
  if (this->target_device_id().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_target_device_id());
  }

  // string action_type = 3;
  if (this->action_type().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_action_type());
  }

  // string trigger_reason = 4;
  if (this->trigger_reason().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_trigger_reason());
  }

  // int64 issued_timestamp_ns = 5;
  if (this->issued_timestamp_ns() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_issued_timestamp_ns());
  }

  // int64 processed_timestamp_ns = 6;
  if (this->processed_timestamp_ns() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_processed_timestamp_ns());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FailsafeCommandProto::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sftwin.failsafe.FailsafeCommandProto)
  GOOGLE_DCHECK_NE(&from, this);
  const FailsafeCommandProto* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<FailsafeCommandProto>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sftwin.failsafe.FailsafeCommandProto)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sftwin.failsafe.FailsafeCommandProto)
    MergeFrom(*source);
  }
}

void FailsafeCommandProto::MergeFrom(const FailsafeCommandProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sftwin.failsafe.FailsafeCommandProto)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.command_id().size() > 0) {
    _internal_set_command_id(from._internal_command_id());
  }
  if (from.target_device_id().size() > 0) {
    _internal_set_target_device_id(from._internal_target_device_id());
  }
  if (from.action_type().size() > 0) {
    _internal_set_action_type(from._internal_action_type());
  }
  if (from.trigger_reason().size() > 0) {
    _internal_set_trigger_reason(from._internal_trigger_reason());
  }
  if (from.issued_timestamp_ns() != 0) {
    _internal_set_issued_timestamp_ns(from._internal_issued_timestamp_ns());
  }
  if (from.processed_timestamp_ns() != 0) {
    _internal_set_processed_timestamp_ns(from._internal_processed_timestamp_ns());
  }
}

void FailsafeCommandProto::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sftwin.failsafe.FailsafeCommandProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FailsafeCommandProto::CopyFrom(const FailsafeCommandProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sftwin.failsafe.FailsafeCommandProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FailsafeCommandProto::IsInitialized() const {
  return true;
}

void FailsafeCommandProto::InternalSwap(FailsafeCommandProto* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  command_id_.Swap(&other->command_id_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  target_device_id_.Swap(&other->target_device_id_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  action_type_.Swap(&other->action_type_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  trigger_reason_.Swap(&other->trigger_reason_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FailsafeCommandProto, processed_timestamp_ns_)
      + sizeof(FailsafeCommandProto::processed_timestamp_ns_)
      - PROTOBUF_FIELD_OFFSET(FailsafeCommandProto, issued_timestamp_ns_)>(
          reinterpret_cast<char*>(&issued_timestamp_ns_),
          reinterpret_cast<char*>(&other->issued_timestamp_ns_));
}

::PROTOBUF_NAMESPACE_ID::Metadata FailsafeCommandProto::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace failsafe
}  // namespace sftwin
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::sftwin::failsafe::FailsafeCommandProto* Arena::CreateMaybeMessage< ::sftwin::failsafe::FailsafeCommandProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sftwin::failsafe::FailsafeCommandProto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
