// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integration_event.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_integration_5fevent_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_integration_5fevent_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/any.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_integration_5fevent_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_integration_5fevent_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_integration_5fevent_2eproto;
namespace sftwin {
namespace eventbus {
class EventHeader;
class EventHeaderDefaultTypeInternal;
extern EventHeaderDefaultTypeInternal _EventHeader_default_instance_;
class IntegrationEventProto;
class IntegrationEventProtoDefaultTypeInternal;
extern IntegrationEventProtoDefaultTypeInternal _IntegrationEventProto_default_instance_;
}  // namespace eventbus
}  // namespace sftwin
PROTOBUF_NAMESPACE_OPEN
template<> ::sftwin::eventbus::EventHeader* Arena::CreateMaybeMessage<::sftwin::eventbus::EventHeader>(Arena*);
template<> ::sftwin::eventbus::IntegrationEventProto* Arena::CreateMaybeMessage<::sftwin::eventbus::IntegrationEventProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sftwin {
namespace eventbus {

// ===================================================================

class EventHeader PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sftwin.eventbus.EventHeader) */ {
 public:
  inline EventHeader() : EventHeader(nullptr) {};
  virtual ~EventHeader();

  EventHeader(const EventHeader& from);
  EventHeader(EventHeader&& from) noexcept
    : EventHeader() {
    *this = ::std::move(from);
  }

  inline EventHeader& operator=(const EventHeader& from) {
    CopyFrom(from);
    return *this;
  }
  inline EventHeader& operator=(EventHeader&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EventHeader& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EventHeader* internal_default_instance() {
    return reinterpret_cast<const EventHeader*>(
               &_EventHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(EventHeader& a, EventHeader& b) {
    a.Swap(&b);
  }
  inline void Swap(EventHeader* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EventHeader* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EventHeader* New() const final {
    return CreateMaybeMessage<EventHeader>(nullptr);
  }

  EventHeader* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EventHeader>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EventHeader& from);
  void MergeFrom(const EventHeader& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EventHeader* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sftwin.eventbus.EventHeader";
  }
  protected:
  explicit EventHeader(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_integration_5fevent_2eproto);
    return ::descriptor_table_integration_5fevent_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEventIdFieldNumber = 1,
    kEventTypeFieldNumber = 2,
    kSourceComponentFieldNumber = 3,
    kTraceIdFieldNumber = 5,
    kTimestampNsFieldNumber = 4,
  };
  // string event_id = 1;
  void clear_event_id();
  const std::string& event_id() const;
  void set_event_id(const std::string& value);
  void set_event_id(std::string&& value);
  void set_event_id(const char* value);
  void set_event_id(const char* value, size_t size);
  std::string* mutable_event_id();
  std::string* release_event_id();
  void set_allocated_event_id(std::string* event_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_event_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_event_id(
      std::string* event_id);
  private:
  const std::string& _internal_event_id() const;
  void _internal_set_event_id(const std::string& value);
  std::string* _internal_mutable_event_id();
  public:

  // string event_type = 2;
  void clear_event_type();
  const std::string& event_type() const;
  void set_event_type(const std::string& value);
  void set_event_type(std::string&& value);
  void set_event_type(const char* value);
  void set_event_type(const char* value, size_t size);
  std::string* mutable_event_type();
  std::string* release_event_type();
  void set_allocated_event_type(std::string* event_type);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_event_type();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_event_type(
      std::string* event_type);
  private:
  const std::string& _internal_event_type() const;
  void _internal_set_event_type(const std::string& value);
  std::string* _internal_mutable_event_type();
  public:

  // string source_component = 3;
  void clear_source_component();
  const std::string& source_component() const;
  void set_source_component(const std::string& value);
  void set_source_component(std::string&& value);
  void set_source_component(const char* value);
  void set_source_component(const char* value, size_t size);
  std::string* mutable_source_component();
  std::string* release_source_component();
  void set_allocated_source_component(std::string* source_component);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_source_component();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_source_component(
      std::string* source_component);
  private:
  const std::string& _internal_source_component() const;
  void _internal_set_source_component(const std::string& value);
  std::string* _internal_mutable_source_component();
  public:

  // string trace_id = 5;
  void clear_trace_id();
  const std::string& trace_id() const;
  void set_trace_id(const std::string& value);
  void set_trace_id(std::string&& value);
  void set_trace_id(const char* value);
  void set_trace_id(const char* value, size_t size);
  std::string* mutable_trace_id();
  std::string* release_trace_id();
  void set_allocated_trace_id(std::string* trace_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_trace_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_trace_id(
      std::string* trace_id);
  private:
  const std::string& _internal_trace_id() const;
  void _internal_set_trace_id(const std::string& value);
  std::string* _internal_mutable_trace_id();
  public:

  // int64 timestamp_ns = 4;
  void clear_timestamp_ns();
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp_ns() const;
  void set_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_timestamp_ns() const;
  void _internal_set_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:sftwin.eventbus.EventHeader)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr event_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr event_type_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr source_component_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr trace_id_;
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp_ns_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_integration_5fevent_2eproto;
};
// -------------------------------------------------------------------

class IntegrationEventProto PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sftwin.eventbus.IntegrationEventProto) */ {
 public:
  inline IntegrationEventProto() : IntegrationEventProto(nullptr) {};
  virtual ~IntegrationEventProto();

  IntegrationEventProto(const IntegrationEventProto& from);
  IntegrationEventProto(IntegrationEventProto&& from) noexcept
    : IntegrationEventProto() {
    *this = ::std::move(from);
  }

  inline IntegrationEventProto& operator=(const IntegrationEventProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline IntegrationEventProto& operator=(IntegrationEventProto&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const IntegrationEventProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IntegrationEventProto* internal_default_instance() {
    return reinterpret_cast<const IntegrationEventProto*>(
               &_IntegrationEventProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(IntegrationEventProto& a, IntegrationEventProto& b) {
    a.Swap(&b);
  }
  inline void Swap(IntegrationEventProto* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IntegrationEventProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline IntegrationEventProto* New() const final {
    return CreateMaybeMessage<IntegrationEventProto>(nullptr);
  }

  IntegrationEventProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<IntegrationEventProto>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const IntegrationEventProto& from);
  void MergeFrom(const IntegrationEventProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IntegrationEventProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sftwin.eventbus.IntegrationEventProto";
  }
  protected:
  explicit IntegrationEventProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_integration_5fevent_2eproto);
    return ::descriptor_table_integration_5fevent_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeaderFieldNumber = 1,
    kPayloadFieldNumber = 2,
  };
  // .sftwin.eventbus.EventHeader header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::sftwin::eventbus::EventHeader& header() const;
  ::sftwin::eventbus::EventHeader* release_header();
  ::sftwin::eventbus::EventHeader* mutable_header();
  void set_allocated_header(::sftwin::eventbus::EventHeader* header);
  private:
  const ::sftwin::eventbus::EventHeader& _internal_header() const;
  ::sftwin::eventbus::EventHeader* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::sftwin::eventbus::EventHeader* header);
  ::sftwin::eventbus::EventHeader* unsafe_arena_release_header();

  // .google.protobuf.Any payload = 2;
  bool has_payload() const;
  private:
  bool _internal_has_payload() const;
  public:
  void clear_payload();
  const PROTOBUF_NAMESPACE_ID::Any& payload() const;
  PROTOBUF_NAMESPACE_ID::Any* release_payload();
  PROTOBUF_NAMESPACE_ID::Any* mutable_payload();
  void set_allocated_payload(PROTOBUF_NAMESPACE_ID::Any* payload);
  private:
  const PROTOBUF_NAMESPACE_ID::Any& _internal_payload() const;
  PROTOBUF_NAMESPACE_ID::Any* _internal_mutable_payload();
  public:
  void unsafe_arena_set_allocated_payload(
      PROTOBUF_NAMESPACE_ID::Any* payload);
  PROTOBUF_NAMESPACE_ID::Any* unsafe_arena_release_payload();

  // @@protoc_insertion_point(class_scope:sftwin.eventbus.IntegrationEventProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::sftwin::eventbus::EventHeader* header_;
  PROTOBUF_NAMESPACE_ID::Any* payload_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_integration_5fevent_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// EventHeader

// string event_id = 1;
inline void EventHeader::clear_event_id() {
  event_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& EventHeader::event_id() const {
  // @@protoc_insertion_point(field_get:sftwin.eventbus.EventHeader.event_id)
  return _internal_event_id();
}
inline void EventHeader::set_event_id(const std::string& value) {
  _internal_set_event_id(value);
  // @@protoc_insertion_point(field_set:sftwin.eventbus.EventHeader.event_id)
}
inline std::string* EventHeader::mutable_event_id() {
  // @@protoc_insertion_point(field_mutable:sftwin.eventbus.EventHeader.event_id)
  return _internal_mutable_event_id();
}
inline const std::string& EventHeader::_internal_event_id() const {
  return event_id_.Get();
}
inline void EventHeader::_internal_set_event_id(const std::string& value) {

  event_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void EventHeader::set_event_id(std::string&& value) {

  event_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:sftwin.eventbus.EventHeader.event_id)
}
inline void EventHeader::set_event_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);

  event_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:sftwin.eventbus.EventHeader.event_id)
}
inline void EventHeader::set_event_id(const char* value,
    size_t size) {

  event_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:sftwin.eventbus.EventHeader.event_id)
}
inline std::string* EventHeader::_internal_mutable_event_id() {

  return event_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* EventHeader::release_event_id() {
  // @@protoc_insertion_point(field_release:sftwin.eventbus.EventHeader.event_id)
  return event_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void EventHeader::set_allocated_event_id(std::string* event_id) {
  if (event_id != nullptr) {

  } else {

  }
  event_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), event_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:sftwin.eventbus.EventHeader.event_id)
}
inline std::string* EventHeader::unsafe_arena_release_event_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:sftwin.eventbus.EventHeader.event_id)
  GOOGLE_DCHECK(GetArena() != nullptr);

  return event_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void EventHeader::unsafe_arena_set_allocated_event_id(
    std::string* event_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (event_id != nullptr) {

  } else {

  }
  event_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      event_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sftwin.eventbus.EventHeader.event_id)
}

// string event_type = 2;
inline void EventHeader::clear_event_type() {
  event_type_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& EventHeader::event_type() const {
  // @@protoc_insertion_point(field_get:sftwin.eventbus.EventHeader.event_type)
  return _internal_event_type();
}
inline void EventHeader::set_event_type(const std::string& value) {
  _internal_set_event_type(value);
  // @@protoc_insertion_point(field_set:sftwin.eventbus.EventHeader.event_type)
}
inline std::string* EventHeader::mutable_event_type() {
  // @@protoc_insertion_point(field_mutable:sftwin.eventbus.EventHeader.event_type)
  return _internal_mutable_event_type();
}
inline const std::string& EventHeader::_internal_event_type() const {
  return event_type_.Get();
}
inline void EventHeader::_internal_set_event_type(const std::string& value) {

  event_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void EventHeader::set_event_type(std::string&& value) {

  event_type_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:sftwin.eventbus.EventHeader.event_type)
}
inline void EventHeader::set_event_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);

  event_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:sftwin.eventbus.EventHeader.event_type)
}
inline void EventHeader::set_event_type(const char* value,
    size_t size) {

  event_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:sftwin.eventbus.EventHeader.event_type)
}
inline std::string* EventHeader::_internal_mutable_event_type() {

  return event_type_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* EventHeader::release_event_type() {
  // @@protoc_insertion_point(field_release:sftwin.eventbus.EventHeader.event_type)
  return event_type_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void EventHeader::set_allocated_event_type(std::string* event_type) {
  if (event_type != nullptr) {

  } else {

  }
  event_type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), event_type,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:sftwin.eventbus.EventHeader.event_type)
}
inline std::string* EventHeader::unsafe_arena_release_event_type() {
  // @@protoc_insertion_point(field_unsafe_arena_release:sftwin.eventbus.EventHeader.event_type)
  GOOGLE_DCHECK(GetArena() != nullptr);

  return event_type_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void EventHeader::unsafe_arena_set_allocated_event_type(
    std::string* event_type) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (event_type != nullptr) {

  } else {

  }
  event_type_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      event_type, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sftwin.eventbus.EventHeader.event_type)
}

// string source_component = 3;
inline void EventHeader::clear_source_component() {
  source_component_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& EventHeader::source_component() const {
  // @@protoc_insertion_point(field_get:sftwin.eventbus.EventHeader.source_component)
  return _internal_source_component();
}
inline void EventHeader::set_source_component(const std::string& value) {
  _internal_set_source_component(value);
  // @@protoc_insertion_point(field_set:sftwin.eventbus.EventHeader.source_component)
}
inline std::string* EventHeader::mutable_source_component() {
  // @@protoc_insertion_point(field_mutable:sftwin.eventbus.EventHeader.source_component)
  return _internal_mutable_source_component();
}
inline const std::string& EventHeader::_internal_source_component() const {
  return source_component_.Get();
}
inline void EventHeader::_internal_set_source_component(const std::string& value) {

  source_component_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void EventHeader::set_source_component(std::string&& value) {

  source_component_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:sftwin.eventbus.EventHeader.source_component)
}
inline void EventHeader::set_source_component(const char* value) {
  GOOGLE_DCHECK(value != nullptr);

  source_component_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:sftwin.eventbus.EventHeader.source_component)
}
inline void EventHeader::set_source_component(const char* value,
    size_t size) {

  source_component_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:sftwin.eventbus.EventHeader.source_component)
}
inline std::string* EventHeader::_internal_mutable_source_component() {

  return source_component_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* EventHeader::release_source_component() {
  // @@protoc_insertion_point(field_release:sftwin.eventbus.EventHeader.source_component)
  return source_component_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void EventHeader::set_allocated_source_component(std::string* source_component) {
  if (source_component != nullptr) {

  } else {

  }
  source_component_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), source_component,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:sftwin.eventbus.EventHeader.source_component)
}
inline std::string* EventHeader::unsafe_arena_release_source_component() {
  // @@protoc_insertion_point(field_unsafe_arena_release:sftwin.eventbus.EventHeader.source_component)
  GOOGLE_DCHECK(GetArena() != nullptr);

  return source_component_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void EventHeader::unsafe_arena_set_allocated_source_component(
    std::string* source_component) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (source_component != nullptr) {

  } else {

  }
  source_component_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      source_component, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sftwin.eventbus.EventHeader.source_component)
}

// int64 timestamp_ns = 4;
inline void EventHeader::clear_timestamp_ns() {
  timestamp_ns_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 EventHeader::_internal_timestamp_ns() const {
  return timestamp_ns_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 EventHeader::timestamp_ns() const {
  // @@protoc_insertion_point(field_get:sftwin.eventbus.EventHeader.timestamp_ns)
  return _internal_timestamp_ns();
}
inline void EventHeader::_internal_set_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value) {

  timestamp_ns_ = value;
}
inline void EventHeader::set_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_timestamp_ns(value);
  // @@protoc_insertion_point(field_set:sftwin.eventbus.EventHeader.timestamp_ns)
}

// string trace_id = 5;
inline void EventHeader::clear_trace_id() {
  trace_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& EventHeader::trace_id() const {
  // @@protoc_insertion_point(field_get:sftwin.eventbus.EventHeader.trace_id)
  return _internal_trace_id();
}
inline void EventHeader::set_trace_id(const std::string& value) {
  _internal_set_trace_id(value);
  // @@protoc_insertion_point(field_set:sftwin.eventbus.EventHeader.trace_id)
}
inline std::string* EventHeader::mutable_trace_id() {
  // @@protoc_insertion_point(field_mutable:sftwin.eventbus.EventHeader.trace_id)
  return _internal_mutable_trace_id();
}
inline const std::string& EventHeader::_internal_trace_id() const {
  return trace_id_.Get();
}
inline void EventHeader::_internal_set_trace_id(const std::string& value) {

  trace_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void EventHeader::set_trace_id(std::string&& value) {

  trace_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:sftwin.eventbus.EventHeader.trace_id)
}
inline void EventHeader::set_trace_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);

  trace_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:sftwin.eventbus.EventHeader.trace_id)
}
inline void EventHeader::set_trace_id(const char* value,
    size_t size) {

  trace_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:sftwin.eventbus.EventHeader.trace_id)
}
inline std::string* EventHeader::_internal_mutable_trace_id() {

  return trace_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* EventHeader::release_trace_id() {
  // @@protoc_insertion_point(field_release:sftwin.eventbus.EventHeader.trace_id)
  return trace_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void EventHeader::set_allocated_trace_id(std::string* trace_id) {
  if (trace_id != nullptr) {

  } else {

  }
  trace_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), trace_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:sftwin.eventbus.EventHeader.trace_id)
}
inline std::string* EventHeader::unsafe_arena_release_trace_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:sftwin.eventbus.EventHeader.trace_id)
  GOOGLE_DCHECK(GetArena() != nullptr);

  return trace_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void EventHeader::unsafe_arena_set_allocated_trace_id(
    std::string* trace_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (trace_id != nullptr) {

  } else {

  }
  trace_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      trace_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sftwin.eventbus.EventHeader.trace_id)
}

// -------------------------------------------------------------------

// IntegrationEventProto

// .sftwin.eventbus.EventHeader header = 1;
inline bool IntegrationEventProto::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool IntegrationEventProto::has_header() const {
  return _internal_has_header();
}
inline void IntegrationEventProto::clear_header() {
  if (GetArena() == nullptr && header_ != nullptr) {
    delete header_;
  }
  header_ = nullptr;
}
inline const ::sftwin::eventbus::EventHeader& IntegrationEventProto::_internal_header() const {
  const ::sftwin::eventbus::EventHeader* p = header_;
  return p != nullptr ? *p : *reinterpret_cast<const ::sftwin::eventbus::EventHeader*>(
      &::sftwin::eventbus::_EventHeader_default_instance_);
}
inline const ::sftwin::eventbus::EventHeader& IntegrationEventProto::header() const {
  // @@protoc_insertion_point(field_get:sftwin.eventbus.IntegrationEventProto.header)
  return _internal_header();
}
inline void IntegrationEventProto::unsafe_arena_set_allocated_header(
    ::sftwin::eventbus::EventHeader* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {

  } else {

  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sftwin.eventbus.IntegrationEventProto.header)
}
inline ::sftwin::eventbus::EventHeader* IntegrationEventProto::release_header() {
  auto temp = unsafe_arena_release_header();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::sftwin::eventbus::EventHeader* IntegrationEventProto::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:sftwin.eventbus.IntegrationEventProto.header)

  ::sftwin::eventbus::EventHeader* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::sftwin::eventbus::EventHeader* IntegrationEventProto::_internal_mutable_header() {

  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::sftwin::eventbus::EventHeader>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::sftwin::eventbus::EventHeader* IntegrationEventProto::mutable_header() {
  // @@protoc_insertion_point(field_mutable:sftwin.eventbus.IntegrationEventProto.header)
  return _internal_mutable_header();
}
inline void IntegrationEventProto::set_allocated_header(::sftwin::eventbus::EventHeader* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete header_;
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(header);
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }

  } else {

  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:sftwin.eventbus.IntegrationEventProto.header)
}

// .google.protobuf.Any payload = 2;
inline bool IntegrationEventProto::_internal_has_payload() const {
  return this != internal_default_instance() && payload_ != nullptr;
}
inline bool IntegrationEventProto::has_payload() const {
  return _internal_has_payload();
}
inline const PROTOBUF_NAMESPACE_ID::Any& IntegrationEventProto::_internal_payload() const {
  const PROTOBUF_NAMESPACE_ID::Any* p = payload_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Any*>(
      &PROTOBUF_NAMESPACE_ID::_Any_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Any& IntegrationEventProto::payload() const {
  // @@protoc_insertion_point(field_get:sftwin.eventbus.IntegrationEventProto.payload)
  return _internal_payload();
}
inline void IntegrationEventProto::unsafe_arena_set_allocated_payload(
    PROTOBUF_NAMESPACE_ID::Any* payload) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(payload_);
  }
  payload_ = payload;
  if (payload) {

  } else {

  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sftwin.eventbus.IntegrationEventProto.payload)
}
inline PROTOBUF_NAMESPACE_ID::Any* IntegrationEventProto::release_payload() {
  auto temp = unsafe_arena_release_payload();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Any* IntegrationEventProto::unsafe_arena_release_payload() {
  // @@protoc_insertion_point(field_release:sftwin.eventbus.IntegrationEventProto.payload)

  PROTOBUF_NAMESPACE_ID::Any* temp = payload_;
  payload_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Any* IntegrationEventProto::_internal_mutable_payload() {

  if (payload_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Any>(GetArena());
    payload_ = p;
  }
  return payload_;
}
inline PROTOBUF_NAMESPACE_ID::Any* IntegrationEventProto::mutable_payload() {
  // @@protoc_insertion_point(field_mutable:sftwin.eventbus.IntegrationEventProto.payload)
  return _internal_mutable_payload();
}
inline void IntegrationEventProto::set_allocated_payload(PROTOBUF_NAMESPACE_ID::Any* payload) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(payload_);
  }
  if (payload) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(payload)->GetArena();
    if (message_arena != submessage_arena) {
      payload = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, payload, submessage_arena);
    }

  } else {

  }
  payload_ = payload;
  // @@protoc_insertion_point(field_set_allocated:sftwin.eventbus.IntegrationEventProto.payload)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace eventbus
}  // namespace sftwin

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_integration_5fevent_2eproto
