// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry_packet.proto

#include "telemetry_packet.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_telemetry_5fpacket_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_DetectedObject_telemetry_5fpacket_2eproto;
namespace sftwin {
namespace telemetry {
class DetectedObjectDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<DetectedObject> _instance;
} _DetectedObject_default_instance_;
class TelemetryPacketProtoDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<TelemetryPacketProto> _instance;
} _TelemetryPacketProto_default_instance_;
}  // namespace telemetry
}  // namespace sftwin
static void InitDefaultsscc_info_DetectedObject_telemetry_5fpacket_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::sftwin::telemetry::_DetectedObject_default_instance_;
    new (ptr) ::sftwin::telemetry::DetectedObject();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::sftwin::telemetry::DetectedObject::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_DetectedObject_telemetry_5fpacket_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_DetectedObject_telemetry_5fpacket_2eproto}, {}};

static void InitDefaultsscc_info_TelemetryPacketProto_telemetry_5fpacket_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::sftwin::telemetry::_TelemetryPacketProto_default_instance_;
    new (ptr) ::sftwin::telemetry::TelemetryPacketProto();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::sftwin::telemetry::TelemetryPacketProto::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_TelemetryPacketProto_telemetry_5fpacket_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_TelemetryPacketProto_telemetry_5fpacket_2eproto}, {
      &scc_info_DetectedObject_telemetry_5fpacket_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_telemetry_5fpacket_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_telemetry_5fpacket_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_telemetry_5fpacket_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_telemetry_5fpacket_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sftwin::telemetry::DetectedObject, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::sftwin::telemetry::DetectedObject, class_name_),
  PROTOBUF_FIELD_OFFSET(::sftwin::telemetry::DetectedObject, confidence_),
  PROTOBUF_FIELD_OFFSET(::sftwin::telemetry::DetectedObject, bbox_),
  PROTOBUF_FIELD_OFFSET(::sftwin::telemetry::TelemetryPacketProto, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::sftwin::telemetry::TelemetryPacketProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::sftwin::telemetry::TelemetryPacketProto, device_id_),
  PROTOBUF_FIELD_OFFSET(::sftwin::telemetry::TelemetryPacketProto, timestamp_ns_),
  PROTOBUF_FIELD_OFFSET(::sftwin::telemetry::TelemetryPacketProto, joint_positions_),
  PROTOBUF_FIELD_OFFSET(::sftwin::telemetry::TelemetryPacketProto, joint_torques_),
  PROTOBUF_FIELD_OFFSET(::sftwin::telemetry::TelemetryPacketProto, packml_state_),
  PROTOBUF_FIELD_OFFSET(::sftwin::telemetry::TelemetryPacketProto, is_warning_),
  PROTOBUF_FIELD_OFFSET(::sftwin::telemetry::TelemetryPacketProto, detected_objects_),
  PROTOBUF_FIELD_OFFSET(::sftwin::telemetry::TelemetryPacketProto, anomaly_score_),
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  0,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::sftwin::telemetry::DetectedObject)},
  { 8, 21, sizeof(::sftwin::telemetry::TelemetryPacketProto)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::sftwin::telemetry::_DetectedObject_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::sftwin::telemetry::_TelemetryPacketProto_default_instance_),
};

const char descriptor_table_protodef_telemetry_5fpacket_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\026telemetry_packet.proto\022\020sftwin.telemet"
  "ry\"F\n\016DetectedObject\022\022\n\nclass_name\030\001 \001(\t"
  "\022\022\n\nconfidence\030\002 \001(\002\022\014\n\004bbox\030\003 \003(\002\"\203\002\n\024T"
  "elemetryPacketProto\022\021\n\tdevice_id\030\001 \001(\t\022\024"
  "\n\014timestamp_ns\030\002 \001(\003\022\027\n\017joint_positions\030"
  "\003 \003(\001\022\025\n\rjoint_torques\030\004 \003(\001\022\024\n\014packml_s"
  "tate\030\005 \001(\t\022\022\n\nis_warning\030\006 \001(\010\022:\n\020detect"
  "ed_objects\030\007 \003(\0132 .sftwin.telemetry.Dete"
  "ctedObject\022\032\n\ranomaly_score\030\010 \001(\002H\000\210\001\001B\020"
  "\n\016_anomaly_scoreb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_telemetry_5fpacket_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_telemetry_5fpacket_2eproto_sccs[2] = {
  &scc_info_DetectedObject_telemetry_5fpacket_2eproto.base,
  &scc_info_TelemetryPacketProto_telemetry_5fpacket_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_telemetry_5fpacket_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_telemetry_5fpacket_2eproto = {
  false, false, descriptor_table_protodef_telemetry_5fpacket_2eproto, "telemetry_packet.proto", 384,
  &descriptor_table_telemetry_5fpacket_2eproto_once, descriptor_table_telemetry_5fpacket_2eproto_sccs, descriptor_table_telemetry_5fpacket_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_telemetry_5fpacket_2eproto::offsets,
  file_level_metadata_telemetry_5fpacket_2eproto, 2, file_level_enum_descriptors_telemetry_5fpacket_2eproto, file_level_service_descriptors_telemetry_5fpacket_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_telemetry_5fpacket_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_telemetry_5fpacket_2eproto)), true);
namespace sftwin {
namespace telemetry {

// ===================================================================

void DetectedObject::InitAsDefaultInstance() {
}
class DetectedObject::_Internal {
 public:
};

DetectedObject::DetectedObject(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  bbox_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:sftwin.telemetry.DetectedObject)
}
DetectedObject::DetectedObject(const DetectedObject& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      bbox_(from.bbox_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  class_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_class_name().empty()) {
    class_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_class_name(),
      GetArena());
  }
  confidence_ = from.confidence_;
  // @@protoc_insertion_point(copy_constructor:sftwin.telemetry.DetectedObject)
}

void DetectedObject::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_DetectedObject_telemetry_5fpacket_2eproto.base);
  class_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  confidence_ = 0;
}

DetectedObject::~DetectedObject() {
  // @@protoc_insertion_point(destructor:sftwin.telemetry.DetectedObject)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void DetectedObject::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  class_name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void DetectedObject::ArenaDtor(void* object) {
  DetectedObject* _this = reinterpret_cast< DetectedObject* >(object);
  (void)_this;
}
void DetectedObject::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void DetectedObject::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DetectedObject& DetectedObject::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_DetectedObject_telemetry_5fpacket_2eproto.base);
  return *internal_default_instance();
}


void DetectedObject::Clear() {
// @@protoc_insertion_point(message_clear_start:sftwin.telemetry.DetectedObject)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  bbox_.Clear();
  class_name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  confidence_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DetectedObject::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string class_name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_class_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "sftwin.telemetry.DetectedObject.class_name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // float confidence = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21)) {
          confidence_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float bbox = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_bbox(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29) {
          _internal_add_bbox(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* DetectedObject::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sftwin.telemetry.DetectedObject)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string class_name = 1;
  if (this->class_name().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_class_name().data(), static_cast<int>(this->_internal_class_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sftwin.telemetry.DetectedObject.class_name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_class_name(), target);
  }

  // float confidence = 2;
  if (!(this->confidence() <= 0 && this->confidence() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(2, this->_internal_confidence(), target);
  }

  // repeated float bbox = 3;
  if (this->_internal_bbox_size() > 0) {
    target = stream->WriteFixedPacked(3, _internal_bbox(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sftwin.telemetry.DetectedObject)
  return target;
}

size_t DetectedObject::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sftwin.telemetry.DetectedObject)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float bbox = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_bbox_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _bbox_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // string class_name = 1;
  if (this->class_name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_class_name());
  }

  // float confidence = 2;
  if (!(this->confidence() <= 0 && this->confidence() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DetectedObject::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sftwin.telemetry.DetectedObject)
  GOOGLE_DCHECK_NE(&from, this);
  const DetectedObject* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<DetectedObject>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sftwin.telemetry.DetectedObject)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sftwin.telemetry.DetectedObject)
    MergeFrom(*source);
  }
}

void DetectedObject::MergeFrom(const DetectedObject& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sftwin.telemetry.DetectedObject)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  bbox_.MergeFrom(from.bbox_);
  if (from.class_name().size() > 0) {
    _internal_set_class_name(from._internal_class_name());
  }
  if (!(from.confidence() <= 0 && from.confidence() >= 0)) {
    _internal_set_confidence(from._internal_confidence());
  }
}

void DetectedObject::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sftwin.telemetry.DetectedObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DetectedObject::CopyFrom(const DetectedObject& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sftwin.telemetry.DetectedObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DetectedObject::IsInitialized() const {
  return true;
}

void DetectedObject::InternalSwap(DetectedObject* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  bbox_.InternalSwap(&other->bbox_);
  class_name_.Swap(&other->class_name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(confidence_, other->confidence_);
}

::PROTOBUF_NAMESPACE_ID::Metadata DetectedObject::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void TelemetryPacketProto::InitAsDefaultInstance() {
}
class TelemetryPacketProto::_Internal {
 public:
  using HasBits = decltype(std::declval<TelemetryPacketProto>()._has_bits_);
  static void set_has_anomaly_score(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

TelemetryPacketProto::TelemetryPacketProto(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  joint_positions_(arena),
  joint_torques_(arena),
  detected_objects_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:sftwin.telemetry.TelemetryPacketProto)
}
TelemetryPacketProto::TelemetryPacketProto(const TelemetryPacketProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_),
      joint_positions_(from.joint_positions_),
      joint_torques_(from.joint_torques_),
      detected_objects_(from.detected_objects_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  device_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_device_id().empty()) {
    device_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_device_id(),
      GetArena());
  }
  packml_state_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_packml_state().empty()) {
    packml_state_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_packml_state(),
      GetArena());
  }
  ::memcpy(&timestamp_ns_, &from.timestamp_ns_,
    static_cast<size_t>(reinterpret_cast<char*>(&anomaly_score_) -
    reinterpret_cast<char*>(&timestamp_ns_)) + sizeof(anomaly_score_));
  // @@protoc_insertion_point(copy_constructor:sftwin.telemetry.TelemetryPacketProto)
}

void TelemetryPacketProto::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_TelemetryPacketProto_telemetry_5fpacket_2eproto.base);
  device_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  packml_state_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&timestamp_ns_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&anomaly_score_) -
      reinterpret_cast<char*>(&timestamp_ns_)) + sizeof(anomaly_score_));
}

TelemetryPacketProto::~TelemetryPacketProto() {
  // @@protoc_insertion_point(destructor:sftwin.telemetry.TelemetryPacketProto)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void TelemetryPacketProto::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  device_id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  packml_state_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void TelemetryPacketProto::ArenaDtor(void* object) {
  TelemetryPacketProto* _this = reinterpret_cast< TelemetryPacketProto* >(object);
  (void)_this;
}
void TelemetryPacketProto::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void TelemetryPacketProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TelemetryPacketProto& TelemetryPacketProto::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_TelemetryPacketProto_telemetry_5fpacket_2eproto.base);
  return *internal_default_instance();
}


void TelemetryPacketProto::Clear() {
// @@protoc_insertion_point(message_clear_start:sftwin.telemetry.TelemetryPacketProto)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  joint_positions_.Clear();
  joint_torques_.Clear();
  detected_objects_.Clear();
  device_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  packml_state_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&timestamp_ns_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&is_warning_) -
      reinterpret_cast<char*>(&timestamp_ns_)) + sizeof(is_warning_));
  anomaly_score_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TelemetryPacketProto::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string device_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_device_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "sftwin.telemetry.TelemetryPacketProto.device_id"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 timestamp_ns = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          timestamp_ns_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated double joint_positions = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_joint_positions(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 25) {
          _internal_add_joint_positions(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // repeated double joint_torques = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_joint_torques(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 33) {
          _internal_add_joint_torques(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // string packml_state = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          auto str = _internal_mutable_packml_state();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "sftwin.telemetry.TelemetryPacketProto.packml_state"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool is_warning = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          is_warning_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .sftwin.telemetry.DetectedObject detected_objects = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_detected_objects(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<58>(ptr));
        } else goto handle_unusual;
        continue;
      // float anomaly_score = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 69)) {
          _Internal::set_has_anomaly_score(&has_bits);
          anomaly_score_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* TelemetryPacketProto::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sftwin.telemetry.TelemetryPacketProto)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string device_id = 1;
  if (this->device_id().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_device_id().data(), static_cast<int>(this->_internal_device_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sftwin.telemetry.TelemetryPacketProto.device_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_device_id(), target);
  }

  // int64 timestamp_ns = 2;
  if (this->timestamp_ns() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(2, this->_internal_timestamp_ns(), target);
  }

  // repeated double joint_positions = 3;
  if (this->_internal_joint_positions_size() > 0) {
    target = stream->WriteFixedPacked(3, _internal_joint_positions(), target);
  }

  // repeated double joint_torques = 4;
  if (this->_internal_joint_torques_size() > 0) {
    target = stream->WriteFixedPacked(4, _internal_joint_torques(), target);
  }

  // string packml_state = 5;
  if (this->packml_state().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_packml_state().data(), static_cast<int>(this->_internal_packml_state().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sftwin.telemetry.TelemetryPacketProto.packml_state");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_packml_state(), target);
  }

  // bool is_warning = 6;
  if (this->is_warning() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(6, this->_internal_is_warning(), target);
  }

  // repeated .sftwin.telemetry.DetectedObject detected_objects = 7;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_detected_objects_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(7, this->_internal_detected_objects(i), target, stream);
  }

  // float anomaly_score = 8;
  if (_internal_has_anomaly_score()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(8, this->_internal_anomaly_score(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sftwin.telemetry.TelemetryPacketProto)
  return target;
}

size_t TelemetryPacketProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sftwin.telemetry.TelemetryPacketProto)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated double joint_positions = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_joint_positions_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _joint_positions_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated double joint_torques = 4;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_joint_torques_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _joint_torques_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated .sftwin.telemetry.DetectedObject detected_objects = 7;
  total_size += 1UL * this->_internal_detected_objects_size();
  for (const auto& msg : this->detected_objects_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string device_id = 1;
  if (this->device_id().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_device_id());
  }

  // string packml_state = 5;
  if (this->packml_state().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_packml_state());
  }

  // int64 timestamp_ns = 2;
  if (this->timestamp_ns() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_timestamp_ns());
  }

  // bool is_warning = 6;
  if (this->is_warning() != 0) {
    total_size += 1 + 1;
  }

  // float anomaly_score = 8;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TelemetryPacketProto::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sftwin.telemetry.TelemetryPacketProto)
  GOOGLE_DCHECK_NE(&from, this);
  const TelemetryPacketProto* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<TelemetryPacketProto>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sftwin.telemetry.TelemetryPacketProto)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sftwin.telemetry.TelemetryPacketProto)
    MergeFrom(*source);
  }
}

void TelemetryPacketProto::MergeFrom(const TelemetryPacketProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sftwin.telemetry.TelemetryPacketProto)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  joint_positions_.MergeFrom(from.joint_positions_);
  joint_torques_.MergeFrom(from.joint_torques_);
  detected_objects_.MergeFrom(from.detected_objects_);
  if (from.device_id().size() > 0) {
    _internal_set_device_id(from._internal_device_id());
  }
  if (from.packml_state().size() > 0) {
    _internal_set_packml_state(from._internal_packml_state());
  }
  if (from.timestamp_ns() != 0) {
    _internal_set_timestamp_ns(from._internal_timestamp_ns());
  }
  if (from.is_warning() != 0) {
    _internal_set_is_warning(from._internal_is_warning());
  }
  if (from._internal_has_anomaly_score()) {
    _internal_set_anomaly_score(from._internal_anomaly_score());
  }
}

void TelemetryPacketProto::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sftwin.telemetry.TelemetryPacketProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TelemetryPacketProto::CopyFrom(const TelemetryPacketProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sftwin.telemetry.TelemetryPacketProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TelemetryPacketProto::IsInitialized() const {
  return true;
}

void TelemetryPacketProto::InternalSwap(TelemetryPacketProto* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  joint_positions_.InternalSwap(&other->joint_positions_);
  joint_torques_.InternalSwap(&other->joint_torques_);
  detected_objects_.InternalSwap(&other->detected_objects_);
  device_id_.Swap(&other->device_id_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  packml_state_.Swap(&other->packml_state_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TelemetryPacketProto, anomaly_score_)
      + sizeof(TelemetryPacketProto::anomaly_score_)
      - PROTOBUF_FIELD_OFFSET(TelemetryPacketProto, timestamp_ns_)>(
          reinterpret_cast<char*>(&timestamp_ns_),
          reinterpret_cast<char*>(&other->timestamp_ns_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TelemetryPacketProto::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace telemetry
}  // namespace sftwin
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::sftwin::telemetry::DetectedObject* Arena::CreateMaybeMessage< ::sftwin::telemetry::DetectedObject >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sftwin::telemetry::DetectedObject >(arena);
}
template<> PROTOBUF_NOINLINE ::sftwin::telemetry::TelemetryPacketProto* Arena::CreateMaybeMessage< ::sftwin::telemetry::TelemetryPacketProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sftwin::telemetry::TelemetryPacketProto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
