// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry_packet.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_telemetry_5fpacket_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_telemetry_5fpacket_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_telemetry_5fpacket_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_telemetry_5fpacket_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_telemetry_5fpacket_2eproto;
namespace sftwin {
namespace telemetry {
class DetectedObject;
class DetectedObjectDefaultTypeInternal;
extern DetectedObjectDefaultTypeInternal _DetectedObject_default_instance_;
class TelemetryPacketProto;
class TelemetryPacketProtoDefaultTypeInternal;
extern TelemetryPacketProtoDefaultTypeInternal _TelemetryPacketProto_default_instance_;
}  // namespace telemetry
}  // namespace sftwin
PROTOBUF_NAMESPACE_OPEN
template<> ::sftwin::telemetry::DetectedObject* Arena::CreateMaybeMessage<::sftwin::telemetry::DetectedObject>(Arena*);
template<> ::sftwin::telemetry::TelemetryPacketProto* Arena::CreateMaybeMessage<::sftwin::telemetry::TelemetryPacketProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sftwin {
namespace telemetry {

// ===================================================================

class DetectedObject PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sftwin.telemetry.DetectedObject) */ {
 public:
  inline DetectedObject() : DetectedObject(nullptr) {};
  virtual ~DetectedObject();

  DetectedObject(const DetectedObject& from);
  DetectedObject(DetectedObject&& from) noexcept
    : DetectedObject() {
    *this = ::std::move(from);
  }

  inline DetectedObject& operator=(const DetectedObject& from) {
    CopyFrom(from);
    return *this;
  }
  inline DetectedObject& operator=(DetectedObject&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DetectedObject& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DetectedObject* internal_default_instance() {
    return reinterpret_cast<const DetectedObject*>(
               &_DetectedObject_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DetectedObject& a, DetectedObject& b) {
    a.Swap(&b);
  }
  inline void Swap(DetectedObject* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DetectedObject* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DetectedObject* New() const final {
    return CreateMaybeMessage<DetectedObject>(nullptr);
  }

  DetectedObject* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DetectedObject>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DetectedObject& from);
  void MergeFrom(const DetectedObject& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DetectedObject* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sftwin.telemetry.DetectedObject";
  }
  protected:
  explicit DetectedObject(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_telemetry_5fpacket_2eproto);
    return ::descriptor_table_telemetry_5fpacket_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBboxFieldNumber = 3,
    kClassNameFieldNumber = 1,
    kConfidenceFieldNumber = 2,
  };
  // repeated float bbox = 3;
  int bbox_size() const;
  private:
  int _internal_bbox_size() const;
  public:
  void clear_bbox();
  private:
  float _internal_bbox(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_bbox() const;
  void _internal_add_bbox(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_bbox();
  public:
  float bbox(int index) const;
  void set_bbox(int index, float value);
  void add_bbox(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      bbox() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_bbox();

  // string class_name = 1;
  void clear_class_name();
  const std::string& class_name() const;
  void set_class_name(const std::string& value);
  void set_class_name(std::string&& value);
  void set_class_name(const char* value);
  void set_class_name(const char* value, size_t size);
  std::string* mutable_class_name();
  std::string* release_class_name();
  void set_allocated_class_name(std::string* class_name);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_class_name();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_class_name(
      std::string* class_name);
  private:
  const std::string& _internal_class_name() const;
  void _internal_set_class_name(const std::string& value);
  std::string* _internal_mutable_class_name();
  public:

  // float confidence = 2;
  void clear_confidence();
  float confidence() const;
  void set_confidence(float value);
  private:
  float _internal_confidence() const;
  void _internal_set_confidence(float value);
  public:

  // @@protoc_insertion_point(class_scope:sftwin.telemetry.DetectedObject)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > bbox_;
  mutable std::atomic<int> _bbox_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr class_name_;
  float confidence_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_telemetry_5fpacket_2eproto;
};
// -------------------------------------------------------------------

class TelemetryPacketProto PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sftwin.telemetry.TelemetryPacketProto) */ {
 public:
  inline TelemetryPacketProto() : TelemetryPacketProto(nullptr) {};
  virtual ~TelemetryPacketProto();

  TelemetryPacketProto(const TelemetryPacketProto& from);
  TelemetryPacketProto(TelemetryPacketProto&& from) noexcept
    : TelemetryPacketProto() {
    *this = ::std::move(from);
  }

  inline TelemetryPacketProto& operator=(const TelemetryPacketProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline TelemetryPacketProto& operator=(TelemetryPacketProto&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TelemetryPacketProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TelemetryPacketProto* internal_default_instance() {
    return reinterpret_cast<const TelemetryPacketProto*>(
               &_TelemetryPacketProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(TelemetryPacketProto& a, TelemetryPacketProto& b) {
    a.Swap(&b);
  }
  inline void Swap(TelemetryPacketProto* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TelemetryPacketProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TelemetryPacketProto* New() const final {
    return CreateMaybeMessage<TelemetryPacketProto>(nullptr);
  }

  TelemetryPacketProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TelemetryPacketProto>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TelemetryPacketProto& from);
  void MergeFrom(const TelemetryPacketProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TelemetryPacketProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sftwin.telemetry.TelemetryPacketProto";
  }
  protected:
  explicit TelemetryPacketProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_telemetry_5fpacket_2eproto);
    return ::descriptor_table_telemetry_5fpacket_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kJointPositionsFieldNumber = 3,
    kJointTorquesFieldNumber = 4,
    kDetectedObjectsFieldNumber = 7,
    kDeviceIdFieldNumber = 1,
    kPackmlStateFieldNumber = 5,
    kTimestampNsFieldNumber = 2,
    kIsWarningFieldNumber = 6,
    kAnomalyScoreFieldNumber = 8,
  };
  // repeated double joint_positions = 3;
  int joint_positions_size() const;
  private:
  int _internal_joint_positions_size() const;
  public:
  void clear_joint_positions();
  private:
  double _internal_joint_positions(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_joint_positions() const;
  void _internal_add_joint_positions(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_joint_positions();
  public:
  double joint_positions(int index) const;
  void set_joint_positions(int index, double value);
  void add_joint_positions(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      joint_positions() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_joint_positions();

  // repeated double joint_torques = 4;
  int joint_torques_size() const;
  private:
  int _internal_joint_torques_size() const;
  public:
  void clear_joint_torques();
  private:
  double _internal_joint_torques(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_joint_torques() const;
  void _internal_add_joint_torques(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_joint_torques();
  public:
  double joint_torques(int index) const;
  void set_joint_torques(int index, double value);
  void add_joint_torques(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      joint_torques() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_joint_torques();

  // repeated .sftwin.telemetry.DetectedObject detected_objects = 7;
  int detected_objects_size() const;
  private:
  int _internal_detected_objects_size() const;
  public:
  void clear_detected_objects();
  ::sftwin::telemetry::DetectedObject* mutable_detected_objects(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sftwin::telemetry::DetectedObject >*
      mutable_detected_objects();
  private:
  const ::sftwin::telemetry::DetectedObject& _internal_detected_objects(int index) const;
  ::sftwin::telemetry::DetectedObject* _internal_add_detected_objects();
  public:
  const ::sftwin::telemetry::DetectedObject& detected_objects(int index) const;
  ::sftwin::telemetry::DetectedObject* add_detected_objects();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sftwin::telemetry::DetectedObject >&
      detected_objects() const;

  // string device_id = 1;
  void clear_device_id();
  const std::string& device_id() const;
  void set_device_id(const std::string& value);
  void set_device_id(std::string&& value);
  void set_device_id(const char* value);
  void set_device_id(const char* value, size_t size);
  std::string* mutable_device_id();
  std::string* release_device_id();
  void set_allocated_device_id(std::string* device_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_device_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_device_id(
      std::string* device_id);
  private:
  const std::string& _internal_device_id() const;
  void _internal_set_device_id(const std::string& value);
  std::string* _internal_mutable_device_id();
  public:

  // string packml_state = 5;
  void clear_packml_state();
  const std::string& packml_state() const;
  void set_packml_state(const std::string& value);
  void set_packml_state(std::string&& value);
  void set_packml_state(const char* value);
  void set_packml_state(const char* value, size_t size);
  std::string* mutable_packml_state();
  std::string* release_packml_state();
  void set_allocated_packml_state(std::string* packml_state);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_packml_state();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_packml_state(
      std::string* packml_state);
  private:
  const std::string& _internal_packml_state() const;
  void _internal_set_packml_state(const std::string& value);
  std::string* _internal_mutable_packml_state();
  public:

  // int64 timestamp_ns = 2;
  void clear_timestamp_ns();
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp_ns() const;
  void set_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_timestamp_ns() const;
  void _internal_set_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // bool is_warning = 6;
  void clear_is_warning();
  bool is_warning() const;
  void set_is_warning(bool value);
  private:
  bool _internal_is_warning() const;
  void _internal_set_is_warning(bool value);
  public:

  // float anomaly_score = 8;
  bool has_anomaly_score() const;
  private:
  bool _internal_has_anomaly_score() const;
  public:
  void clear_anomaly_score();
  float anomaly_score() const;
  void set_anomaly_score(float value);
  private:
  float _internal_anomaly_score() const;
  void _internal_set_anomaly_score(float value);
  public:

  // @@protoc_insertion_point(class_scope:sftwin.telemetry.TelemetryPacketProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > joint_positions_;
  mutable std::atomic<int> _joint_positions_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > joint_torques_;
  mutable std::atomic<int> _joint_torques_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sftwin::telemetry::DetectedObject > detected_objects_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr device_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr packml_state_;
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp_ns_;
  bool is_warning_;
  float anomaly_score_;
  friend struct ::TableStruct_telemetry_5fpacket_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DetectedObject

// string class_name = 1;
inline void DetectedObject::clear_class_name() {
  class_name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& DetectedObject::class_name() const {
  // @@protoc_insertion_point(field_get:sftwin.telemetry.DetectedObject.class_name)
  return _internal_class_name();
}
inline void DetectedObject::set_class_name(const std::string& value) {
  _internal_set_class_name(value);
  // @@protoc_insertion_point(field_set:sftwin.telemetry.DetectedObject.class_name)
}
inline std::string* DetectedObject::mutable_class_name() {
  // @@protoc_insertion_point(field_mutable:sftwin.telemetry.DetectedObject.class_name)
  return _internal_mutable_class_name();
}
inline const std::string& DetectedObject::_internal_class_name() const {
  return class_name_.Get();
}
inline void DetectedObject::_internal_set_class_name(const std::string& value) {

  class_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void DetectedObject::set_class_name(std::string&& value) {

  class_name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:sftwin.telemetry.DetectedObject.class_name)
}
inline void DetectedObject::set_class_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);

  class_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:sftwin.telemetry.DetectedObject.class_name)
}
inline void DetectedObject::set_class_name(const char* value,
    size_t size) {

  class_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:sftwin.telemetry.DetectedObject.class_name)
}
inline std::string* DetectedObject::_internal_mutable_class_name() {

  return class_name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* DetectedObject::release_class_name() {
  // @@protoc_insertion_point(field_release:sftwin.telemetry.DetectedObject.class_name)
  return class_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void DetectedObject::set_allocated_class_name(std::string* class_name) {
  if (class_name != nullptr) {

  } else {

  }
  class_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), class_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:sftwin.telemetry.DetectedObject.class_name)
}
inline std::string* DetectedObject::unsafe_arena_release_class_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:sftwin.telemetry.DetectedObject.class_name)
  GOOGLE_DCHECK(GetArena() != nullptr);

  return class_name_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void DetectedObject::unsafe_arena_set_allocated_class_name(
    std::string* class_name) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (class_name != nullptr) {

  } else {

  }
  class_name_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      class_name, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sftwin.telemetry.DetectedObject.class_name)
}

// float confidence = 2;
inline void DetectedObject::clear_confidence() {
  confidence_ = 0;
}
inline float DetectedObject::_internal_confidence() const {
  return confidence_;
}
inline float DetectedObject::confidence() const {
  // @@protoc_insertion_point(field_get:sftwin.telemetry.DetectedObject.confidence)
  return _internal_confidence();
}
inline void DetectedObject::_internal_set_confidence(float value) {

  confidence_ = value;
}
inline void DetectedObject::set_confidence(float value) {
  _internal_set_confidence(value);
  // @@protoc_insertion_point(field_set:sftwin.telemetry.DetectedObject.confidence)
}

// repeated float bbox = 3;
inline int DetectedObject::_internal_bbox_size() const {
  return bbox_.size();
}
inline int DetectedObject::bbox_size() const {
  return _internal_bbox_size();
}
inline void DetectedObject::clear_bbox() {
  bbox_.Clear();
}
inline float DetectedObject::_internal_bbox(int index) const {
  return bbox_.Get(index);
}
inline float DetectedObject::bbox(int index) const {
  // @@protoc_insertion_point(field_get:sftwin.telemetry.DetectedObject.bbox)
  return _internal_bbox(index);
}
inline void DetectedObject::set_bbox(int index, float value) {
  bbox_.Set(index, value);
  // @@protoc_insertion_point(field_set:sftwin.telemetry.DetectedObject.bbox)
}
inline void DetectedObject::_internal_add_bbox(float value) {
  bbox_.Add(value);
}
inline void DetectedObject::add_bbox(float value) {
  _internal_add_bbox(value);
  // @@protoc_insertion_point(field_add:sftwin.telemetry.DetectedObject.bbox)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
DetectedObject::_internal_bbox() const {
  return bbox_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
DetectedObject::bbox() const {
  // @@protoc_insertion_point(field_list:sftwin.telemetry.DetectedObject.bbox)
  return _internal_bbox();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
DetectedObject::_internal_mutable_bbox() {
  return &bbox_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
DetectedObject::mutable_bbox() {
  // @@protoc_insertion_point(field_mutable_list:sftwin.telemetry.DetectedObject.bbox)
  return _internal_mutable_bbox();
}

// -------------------------------------------------------------------

// TelemetryPacketProto

// string device_id = 1;
inline void TelemetryPacketProto::clear_device_id() {
  device_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& TelemetryPacketProto::device_id() const {
  // @@protoc_insertion_point(field_get:sftwin.telemetry.TelemetryPacketProto.device_id)
  return _internal_device_id();
}
inline void TelemetryPacketProto::set_device_id(const std::string& value) {
  _internal_set_device_id(value);
  // @@protoc_insertion_point(field_set:sftwin.telemetry.TelemetryPacketProto.device_id)
}
inline std::string* TelemetryPacketProto::mutable_device_id() {
  // @@protoc_insertion_point(field_mutable:sftwin.telemetry.TelemetryPacketProto.device_id)
  return _internal_mutable_device_id();
}
inline const std::string& TelemetryPacketProto::_internal_device_id() const {
  return device_id_.Get();
}
inline void TelemetryPacketProto::_internal_set_device_id(const std::string& value) {

  device_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void TelemetryPacketProto::set_device_id(std::string&& value) {

  device_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:sftwin.telemetry.TelemetryPacketProto.device_id)
}
inline void TelemetryPacketProto::set_device_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);

  device_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:sftwin.telemetry.TelemetryPacketProto.device_id)
}
inline void TelemetryPacketProto::set_device_id(const char* value,
    size_t size) {

  device_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:sftwin.telemetry.TelemetryPacketProto.device_id)
}
inline std::string* TelemetryPacketProto::_internal_mutable_device_id() {

  return device_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* TelemetryPacketProto::release_device_id() {
  // @@protoc_insertion_point(field_release:sftwin.telemetry.TelemetryPacketProto.device_id)
  return device_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TelemetryPacketProto::set_allocated_device_id(std::string* device_id) {
  if (device_id != nullptr) {

  } else {

  }
  device_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), device_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:sftwin.telemetry.TelemetryPacketProto.device_id)
}
inline std::string* TelemetryPacketProto::unsafe_arena_release_device_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:sftwin.telemetry.TelemetryPacketProto.device_id)
  GOOGLE_DCHECK(GetArena() != nullptr);

  return device_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void TelemetryPacketProto::unsafe_arena_set_allocated_device_id(
    std::string* device_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (device_id != nullptr) {

  } else {

  }
  device_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      device_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sftwin.telemetry.TelemetryPacketProto.device_id)
}

// int64 timestamp_ns = 2;
inline void TelemetryPacketProto::clear_timestamp_ns() {
  timestamp_ns_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TelemetryPacketProto::_internal_timestamp_ns() const {
  return timestamp_ns_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TelemetryPacketProto::timestamp_ns() const {
  // @@protoc_insertion_point(field_get:sftwin.telemetry.TelemetryPacketProto.timestamp_ns)
  return _internal_timestamp_ns();
}
inline void TelemetryPacketProto::_internal_set_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value) {

  timestamp_ns_ = value;
}
inline void TelemetryPacketProto::set_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_timestamp_ns(value);
  // @@protoc_insertion_point(field_set:sftwin.telemetry.TelemetryPacketProto.timestamp_ns)
}

// repeated double joint_positions = 3;
inline int TelemetryPacketProto::_internal_joint_positions_size() const {
  return joint_positions_.size();
}
inline int TelemetryPacketProto::joint_positions_size() const {
  return _internal_joint_positions_size();
}
inline void TelemetryPacketProto::clear_joint_positions() {
  joint_positions_.Clear();
}
inline double TelemetryPacketProto::_internal_joint_positions(int index) const {
  return joint_positions_.Get(index);
}
inline double TelemetryPacketProto::joint_positions(int index) const {
  // @@protoc_insertion_point(field_get:sftwin.telemetry.TelemetryPacketProto.joint_positions)
  return _internal_joint_positions(index);
}
inline void TelemetryPacketProto::set_joint_positions(int index, double value) {
  joint_positions_.Set(index, value);
  // @@protoc_insertion_point(field_set:sftwin.telemetry.TelemetryPacketProto.joint_positions)
}
inline void TelemetryPacketProto::_internal_add_joint_positions(double value) {
  joint_positions_.Add(value);
}
inline void TelemetryPacketProto::add_joint_positions(double value) {
  _internal_add_joint_positions(value);
  // @@protoc_insertion_point(field_add:sftwin.telemetry.TelemetryPacketProto.joint_positions)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
TelemetryPacketProto::_internal_joint_positions() const {
  return joint_positions_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
TelemetryPacketProto::joint_positions() const {
  // @@protoc_insertion_point(field_list:sftwin.telemetry.TelemetryPacketProto.joint_positions)
  return _internal_joint_positions();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
TelemetryPacketProto::_internal_mutable_joint_positions() {
  return &joint_positions_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
TelemetryPacketProto::mutable_joint_positions() {
  // @@protoc_insertion_point(field_mutable_list:sftwin.telemetry.TelemetryPacketProto.joint_positions)
  return _internal_mutable_joint_positions();
}

// repeated double joint_torques = 4;
inline int TelemetryPacketProto::_internal_joint_torques_size() const {
  return joint_torques_.size();
}
inline int TelemetryPacketProto::joint_torques_size() const {
  return _internal_joint_torques_size();
}
inline void TelemetryPacketProto::clear_joint_torques() {
  joint_torques_.Clear();
}
inline double TelemetryPacketProto::_internal_joint_torques(int index) const {
  return joint_torques_.Get(index);
}
inline double TelemetryPacketProto::joint_torques(int index) const {
  // @@protoc_insertion_point(field_get:sftwin.telemetry.TelemetryPacketProto.joint_torques)
  return _internal_joint_torques(index);
}
inline void TelemetryPacketProto::set_joint_torques(int index, double value) {
  joint_torques_.Set(index, value);
  // @@protoc_insertion_point(field_set:sftwin.telemetry.TelemetryPacketProto.joint_torques)
}
inline void TelemetryPacketProto::_internal_add_joint_torques(double value) {
  joint_torques_.Add(value);
}
inline void TelemetryPacketProto::add_joint_torques(double value) {
  _internal_add_joint_torques(value);
  // @@protoc_insertion_point(field_add:sftwin.telemetry.TelemetryPacketProto.joint_torques)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
TelemetryPacketProto::_internal_joint_torques() const {
  return joint_torques_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
TelemetryPacketProto::joint_torques() const {
  // @@protoc_insertion_point(field_list:sftwin.telemetry.TelemetryPacketProto.joint_torques)
  return _internal_joint_torques();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
TelemetryPacketProto::_internal_mutable_joint_torques() {
  return &joint_torques_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
TelemetryPacketProto::mutable_joint_torques() {
  // @@protoc_insertion_point(field_mutable_list:sftwin.telemetry.TelemetryPacketProto.joint_torques)
  return _internal_mutable_joint_torques();
}

// string packml_state = 5;
inline void TelemetryPacketProto::clear_packml_state() {
  packml_state_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& TelemetryPacketProto::packml_state() const {
  // @@protoc_insertion_point(field_get:sftwin.telemetry.TelemetryPacketProto.packml_state)
  return _internal_packml_state();
}
inline void TelemetryPacketProto::set_packml_state(const std::string& value) {
  _internal_set_packml_state(value);
  // @@protoc_insertion_point(field_set:sftwin.telemetry.TelemetryPacketProto.packml_state)
}
inline std::string* TelemetryPacketProto::mutable_packml_state() {
  // @@protoc_insertion_point(field_mutable:sftwin.telemetry.TelemetryPacketProto.packml_state)
  return _internal_mutable_packml_state();
}
inline const std::string& TelemetryPacketProto::_internal_packml_state() const {
  return packml_state_.Get();
}
inline void TelemetryPacketProto::_internal_set_packml_state(const std::string& value) {

  packml_state_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void TelemetryPacketProto::set_packml_state(std::string&& value) {

  packml_state_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:sftwin.telemetry.TelemetryPacketProto.packml_state)
}
inline void TelemetryPacketProto::set_packml_state(const char* value) {
  GOOGLE_DCHECK(value != nullptr);

  packml_state_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:sftwin.telemetry.TelemetryPacketProto.packml_state)
}
inline void TelemetryPacketProto::set_packml_state(const char* value,
    size_t size) {

  packml_state_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:sftwin.telemetry.TelemetryPacketProto.packml_state)
}
inline std::string* TelemetryPacketProto::_internal_mutable_packml_state() {

  return packml_state_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* TelemetryPacketProto::release_packml_state() {
  // @@protoc_insertion_point(field_release:sftwin.telemetry.TelemetryPacketProto.packml_state)
  return packml_state_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TelemetryPacketProto::set_allocated_packml_state(std::string* packml_state) {
  if (packml_state != nullptr) {

  } else {

  }
  packml_state_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), packml_state,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:sftwin.telemetry.TelemetryPacketProto.packml_state)
}
inline std::string* TelemetryPacketProto::unsafe_arena_release_packml_state() {
  // @@protoc_insertion_point(field_unsafe_arena_release:sftwin.telemetry.TelemetryPacketProto.packml_state)
  GOOGLE_DCHECK(GetArena() != nullptr);

  return packml_state_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void TelemetryPacketProto::unsafe_arena_set_allocated_packml_state(
    std::string* packml_state) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (packml_state != nullptr) {

  } else {

  }
  packml_state_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      packml_state, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sftwin.telemetry.TelemetryPacketProto.packml_state)
}

// bool is_warning = 6;
inline void TelemetryPacketProto::clear_is_warning() {
  is_warning_ = false;
}
inline bool TelemetryPacketProto::_internal_is_warning() const {
  return is_warning_;
}
inline bool TelemetryPacketProto::is_warning() const {
  // @@protoc_insertion_point(field_get:sftwin.telemetry.TelemetryPacketProto.is_warning)
  return _internal_is_warning();
}
inline void TelemetryPacketProto::_internal_set_is_warning(bool value) {

  is_warning_ = value;
}
inline void TelemetryPacketProto::set_is_warning(bool value) {
  _internal_set_is_warning(value);
  // @@protoc_insertion_point(field_set:sftwin.telemetry.TelemetryPacketProto.is_warning)
}

// repeated .sftwin.telemetry.DetectedObject detected_objects = 7;
inline int TelemetryPacketProto::_internal_detected_objects_size() const {
  return detected_objects_.size();
}
inline int TelemetryPacketProto::detected_objects_size() const {
  return _internal_detected_objects_size();
}
inline void TelemetryPacketProto::clear_detected_objects() {
  detected_objects_.Clear();
}
inline ::sftwin::telemetry::DetectedObject* TelemetryPacketProto::mutable_detected_objects(int index) {
  // @@protoc_insertion_point(field_mutable:sftwin.telemetry.TelemetryPacketProto.detected_objects)
  return detected_objects_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sftwin::telemetry::DetectedObject >*
TelemetryPacketProto::mutable_detected_objects() {
  // @@protoc_insertion_point(field_mutable_list:sftwin.telemetry.TelemetryPacketProto.detected_objects)
  return &detected_objects_;
}
inline const ::sftwin::telemetry::DetectedObject& TelemetryPacketProto::_internal_detected_objects(int index) const {
  return detected_objects_.Get(index);
}
inline const ::sftwin::telemetry::DetectedObject& TelemetryPacketProto::detected_objects(int index) const {
  // @@protoc_insertion_point(field_get:sftwin.telemetry.TelemetryPacketProto.detected_objects)
  return _internal_detected_objects(index);
}
inline ::sftwin::telemetry::DetectedObject* TelemetryPacketProto::_internal_add_detected_objects() {
  return detected_objects_.Add();
}
inline ::sftwin::telemetry::DetectedObject* TelemetryPacketProto::add_detected_objects() {
  // @@protoc_insertion_point(field_add:sftwin.telemetry.TelemetryPacketProto.detected_objects)
  return _internal_add_detected_objects();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::sftwin::telemetry::DetectedObject >&
TelemetryPacketProto::detected_objects() const {
  // @@protoc_insertion_point(field_list:sftwin.telemetry.TelemetryPacketProto.detected_objects)
  return detected_objects_;
}

// float anomaly_score = 8;
inline bool TelemetryPacketProto::_internal_has_anomaly_score() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool TelemetryPacketProto::has_anomaly_score() const {
  return _internal_has_anomaly_score();
}
inline void TelemetryPacketProto::clear_anomaly_score() {
  anomaly_score_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline float TelemetryPacketProto::_internal_anomaly_score() const {
  return anomaly_score_;
}
inline float TelemetryPacketProto::anomaly_score() const {
  // @@protoc_insertion_point(field_get:sftwin.telemetry.TelemetryPacketProto.anomaly_score)
  return _internal_anomaly_score();
}
inline void TelemetryPacketProto::_internal_set_anomaly_score(float value) {
  _has_bits_[0] |= 0x00000001u;
  anomaly_score_ = value;
}
inline void TelemetryPacketProto::set_anomaly_score(float value) {
  _internal_set_anomaly_score(value);
  // @@protoc_insertion_point(field_set:sftwin.telemetry.TelemetryPacketProto.anomaly_score)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace telemetry
}  // namespace sftwin

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_telemetry_5fpacket_2eproto
