export enum GlobalErrorCode {
    ERR_COMMON_INVALID_INPUT = 'ERR_COMMON_INVALID_INPUT',
    ERR_TWIN_INVALID_SCHEMA = 'ERR_TWIN_INVALID_SCHEMA',
    ERR_UI_WEBGL_CONTEXT_LOST = 'ERR_UI_WEBGL_CONTEXT_LOST',
    ERR_UI_TELEMETRY_WS_DISCONNECTED = 'ERR_UI_TELEMETRY_WS_DISCONNECTED',
    ERR_UI_ASSET_LOAD_FAILED = 'ERR_UI_ASSET_LOAD_FAILED',
    ERR_UI_ESTOP_LOCKED_INTERACTION = 'ERR_UI_ESTOP_LOCKED_INTERACTION',
    ERR_UI_WEBRTC_STREAM_FAILED = 'ERR_UI_WEBRTC_STREAM_FAILED',
    ERR_UI_SIM_POLL_TIMEOUT = 'ERR_UI_SIM_POLL_TIMEOUT',
    ERR_UI_SIM2REAL_DEPLOY_FAILED = 'ERR_UI_SIM2REAL_DEPLOY_FAILED',
}
