from enum import Enum


class ErrorCodeEnum(str, Enum):
    """SF-Twin 전역 에러 코드 정의 (GTS v2.0 / ITD v1.0 준수)"""

    # Common & Shared Infrastructure
    SUCCESS = "SUCCESS"
    ERR_COMMON_INVALID_INPUT = "ERR_COMMON_INVALID_INPUT"
    ERR_COMMON_UNAUTHORIZED = "ERR_COMMON_UNAUTHORIZED"
    ERR_COMMON_FORBIDDEN = "ERR_COMMON_FORBIDDEN"
    ERR_COMMON_INTERNAL_ERROR = "ERR_COMMON_INTERNAL_ERROR"

    # Shared Component Specific
    ERR_SHARED_UNAUTHORIZED = "ERR_SHARED_UNAUTHORIZED"
    ERR_SHARED_FORBIDDEN = "ERR_SHARED_FORBIDDEN"
    ERR_SHARED_CONFIG_NOT_FOUND = "ERR_SHARED_CONFIG_NOT_FOUND"
    ERR_SHARED_ENCRYPTION_FAILED = "ERR_SHARED_ENCRYPTION_FAILED"
    ERR_SHARED_INTERNAL_ERROR = "ERR_SHARED_INTERNAL_ERROR"

    # Digital Twin
    ERR_TWIN_NOT_FOUND = "ERR_TWIN_NOT_FOUND"
    ERR_TWIN_SYNC_OVER_LIMIT = "ERR_TWIN_SYNC_OVER_LIMIT"

    # Simulation
    ERR_SIM_COLLISION_DETECTED = "ERR_SIM_COLLISION_DETECTED"

    # Edge Control
    ERR_EDGE_COMM_TIMEOUT = "ERR_EDGE_COMM_TIMEOUT"
    ERR_EDGE_FAILSAFE_TRIGGERED = "ERR_EDGE_FAILSAFE_TRIGGERED"
