# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: failsafe_command.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="failsafe_command.proto",
    package="sftwin.failsafe",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x16\x66\x61ilsafe_command.proto\x12\x0fsftwin.failsafe"\xae\x01\n\x14\x46\x61ilsafeCommandProto\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12\x18\n\x10target_device_id\x18\x02 \x01(\t\x12\x13\n\x0b\x61\x63tion_type\x18\x03 \x01(\t\x12\x16\n\x0etrigger_reason\x18\x04 \x01(\t\x12\x1b\n\x13issued_timestamp_ns\x18\x05 \x01(\x03\x12\x1e\n\x16processed_timestamp_ns\x18\x06 \x01(\x03\x62\x06proto3',
)


_FAILSAFECOMMANDPROTO = _descriptor.Descriptor(
    name="FailsafeCommandProto",
    full_name="sftwin.failsafe.FailsafeCommandProto",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="command_id",
            full_name="sftwin.failsafe.FailsafeCommandProto.command_id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="target_device_id",
            full_name="sftwin.failsafe.FailsafeCommandProto.target_device_id",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="action_type",
            full_name="sftwin.failsafe.FailsafeCommandProto.action_type",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="trigger_reason",
            full_name="sftwin.failsafe.FailsafeCommandProto.trigger_reason",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="issued_timestamp_ns",
            full_name="sftwin.failsafe.FailsafeCommandProto.issued_timestamp_ns",
            index=4,
            number=5,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="processed_timestamp_ns",
            full_name="sftwin.failsafe.FailsafeCommandProto.processed_timestamp_ns",
            index=5,
            number=6,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=44,
    serialized_end=218,
)

DESCRIPTOR.message_types_by_name["FailsafeCommandProto"] = _FAILSAFECOMMANDPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FailsafeCommandProto = _reflection.GeneratedProtocolMessageType(
    "FailsafeCommandProto",
    (_message.Message,),
    {
        "DESCRIPTOR": _FAILSAFECOMMANDPROTO,
        "__module__": "failsafe_command_pb2",
        # @@protoc_insertion_point(class_scope:sftwin.failsafe.FailsafeCommandProto)
    },
)
_sym_db.RegisterMessage(FailsafeCommandProto)


# @@protoc_insertion_point(module_scope)
