# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: integration_event.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="integration_event.proto",
    package="sftwin.eventbus",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x17integration_event.proto\x12\x0fsftwin.eventbus\x1a\x19google/protobuf/any.proto"u\n\x0b\x45ventHeader\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x18\n\x10source_component\x18\x03 \x01(\t\x12\x14\n\x0ctimestamp_ns\x18\x04 \x01(\x03\x12\x10\n\x08trace_id\x18\x05 \x01(\t"l\n\x15IntegrationEventProto\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.sftwin.eventbus.EventHeader\x12%\n\x07payload\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Anyb\x06proto3',
    dependencies=[
        google_dot_protobuf_dot_any__pb2.DESCRIPTOR,
    ],
)


_EVENTHEADER = _descriptor.Descriptor(
    name="EventHeader",
    full_name="sftwin.eventbus.EventHeader",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="event_id",
            full_name="sftwin.eventbus.EventHeader.event_id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="event_type",
            full_name="sftwin.eventbus.EventHeader.event_type",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="source_component",
            full_name="sftwin.eventbus.EventHeader.source_component",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="timestamp_ns",
            full_name="sftwin.eventbus.EventHeader.timestamp_ns",
            index=3,
            number=4,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="trace_id",
            full_name="sftwin.eventbus.EventHeader.trace_id",
            index=4,
            number=5,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=71,
    serialized_end=188,
)


_INTEGRATIONEVENTPROTO = _descriptor.Descriptor(
    name="IntegrationEventProto",
    full_name="sftwin.eventbus.IntegrationEventProto",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="header",
            full_name="sftwin.eventbus.IntegrationEventProto.header",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="payload",
            full_name="sftwin.eventbus.IntegrationEventProto.payload",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=190,
    serialized_end=298,
)

_INTEGRATIONEVENTPROTO.fields_by_name["header"].message_type = _EVENTHEADER
_INTEGRATIONEVENTPROTO.fields_by_name["payload"].message_type = (
    google_dot_protobuf_dot_any__pb2._ANY
)
DESCRIPTOR.message_types_by_name["EventHeader"] = _EVENTHEADER
DESCRIPTOR.message_types_by_name["IntegrationEventProto"] = _INTEGRATIONEVENTPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EventHeader = _reflection.GeneratedProtocolMessageType(
    "EventHeader",
    (_message.Message,),
    {
        "DESCRIPTOR": _EVENTHEADER,
        "__module__": "integration_event_pb2",
        # @@protoc_insertion_point(class_scope:sftwin.eventbus.EventHeader)
    },
)
_sym_db.RegisterMessage(EventHeader)

IntegrationEventProto = _reflection.GeneratedProtocolMessageType(
    "IntegrationEventProto",
    (_message.Message,),
    {
        "DESCRIPTOR": _INTEGRATIONEVENTPROTO,
        "__module__": "integration_event_pb2",
        # @@protoc_insertion_point(class_scope:sftwin.eventbus.IntegrationEventProto)
    },
)
_sym_db.RegisterMessage(IntegrationEventProto)


# @@protoc_insertion_point(module_scope)
