# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telemetry_packet.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="telemetry_packet.proto",
    package="sftwin.telemetry",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x16telemetry_packet.proto\x12\x10sftwin.telemetry"F\n\x0e\x44\x65tectedObject\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x0c\n\x04\x62\x62ox\x18\x03 \x03(\x02"\x83\x02\n\x14TelemetryPacketProto\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x14\n\x0ctimestamp_ns\x18\x02 \x01(\x03\x12\x17\n\x0fjoint_positions\x18\x03 \x03(\x01\x12\x15\n\rjoint_torques\x18\x04 \x03(\x01\x12\x14\n\x0cpackml_state\x18\x05 \x01(\t\x12\x12\n\nis_warning\x18\x06 \x01(\x08\x12:\n\x10\x64\x65tected_objects\x18\x07 \x03(\x0b\x32 .sftwin.telemetry.DetectedObject\x12\x1a\n\ranomaly_score\x18\x08 \x01(\x02H\x00\x88\x01\x01\x42\x10\n\x0e_anomaly_scoreb\x06proto3',
)


_DETECTEDOBJECT = _descriptor.Descriptor(
    name="DetectedObject",
    full_name="sftwin.telemetry.DetectedObject",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="class_name",
            full_name="sftwin.telemetry.DetectedObject.class_name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="confidence",
            full_name="sftwin.telemetry.DetectedObject.confidence",
            index=1,
            number=2,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="bbox",
            full_name="sftwin.telemetry.DetectedObject.bbox",
            index=2,
            number=3,
            type=2,
            cpp_type=6,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=44,
    serialized_end=114,
)


_TELEMETRYPACKETPROTO = _descriptor.Descriptor(
    name="TelemetryPacketProto",
    full_name="sftwin.telemetry.TelemetryPacketProto",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="device_id",
            full_name="sftwin.telemetry.TelemetryPacketProto.device_id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="timestamp_ns",
            full_name="sftwin.telemetry.TelemetryPacketProto.timestamp_ns",
            index=1,
            number=2,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="joint_positions",
            full_name="sftwin.telemetry.TelemetryPacketProto.joint_positions",
            index=2,
            number=3,
            type=1,
            cpp_type=5,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="joint_torques",
            full_name="sftwin.telemetry.TelemetryPacketProto.joint_torques",
            index=3,
            number=4,
            type=1,
            cpp_type=5,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="packml_state",
            full_name="sftwin.telemetry.TelemetryPacketProto.packml_state",
            index=4,
            number=5,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="is_warning",
            full_name="sftwin.telemetry.TelemetryPacketProto.is_warning",
            index=5,
            number=6,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="detected_objects",
            full_name="sftwin.telemetry.TelemetryPacketProto.detected_objects",
            index=6,
            number=7,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="anomaly_score",
            full_name="sftwin.telemetry.TelemetryPacketProto.anomaly_score",
            index=7,
            number=8,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="_anomaly_score",
            full_name="sftwin.telemetry.TelemetryPacketProto._anomaly_score",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
    ],
    serialized_start=117,
    serialized_end=376,
)

_TELEMETRYPACKETPROTO.fields_by_name["detected_objects"].message_type = _DETECTEDOBJECT
_TELEMETRYPACKETPROTO.oneofs_by_name["_anomaly_score"].fields.append(
    _TELEMETRYPACKETPROTO.fields_by_name["anomaly_score"]
)
_TELEMETRYPACKETPROTO.fields_by_name["anomaly_score"].containing_oneof = (
    _TELEMETRYPACKETPROTO.oneofs_by_name["_anomaly_score"]
)
DESCRIPTOR.message_types_by_name["DetectedObject"] = _DETECTEDOBJECT
DESCRIPTOR.message_types_by_name["TelemetryPacketProto"] = _TELEMETRYPACKETPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DetectedObject = _reflection.GeneratedProtocolMessageType(
    "DetectedObject",
    (_message.Message,),
    {
        "DESCRIPTOR": _DETECTEDOBJECT,
        "__module__": "telemetry_packet_pb2",
        # @@protoc_insertion_point(class_scope:sftwin.telemetry.DetectedObject)
    },
)
_sym_db.RegisterMessage(DetectedObject)

TelemetryPacketProto = _reflection.GeneratedProtocolMessageType(
    "TelemetryPacketProto",
    (_message.Message,),
    {
        "DESCRIPTOR": _TELEMETRYPACKETPROTO,
        "__module__": "telemetry_packet_pb2",
        # @@protoc_insertion_point(class_scope:sftwin.telemetry.TelemetryPacketProto)
    },
)
_sym_db.RegisterMessage(TelemetryPacketProto)


# @@protoc_insertion_point(module_scope)
