from enum import Enum


class PackMLState(str, Enum):
    OFFLINE = "OFFLINE"
    STOPPED = "STOPPED"
    IDLE = "IDLE"
    STARTING = "STARTING"
    EXECUTE = "EXECUTE"
    HOLDING = "HOLDING"
    HELD = "HELD"
    UNHOLDING = "UNHOLDING"
    SUSPENDED = "SUSPENDED"
    COMPLETING = "COMPLETING"
    COMPLETE = "COMPLETE"
    ABORTING = "ABORTING"
    ABORTED = "ABORTED"
