upstream asset_service {
    server sftwin-asset-svc:8000;
}

upstream sim_service {
    server sftwin-sim-svc:8001;
}

upstream kpi_service {
    server sftwin-kpi-svc:8002;
}

server {
    listen 80;
    server_name localhost;

    # Global Gateway Health Check
    location /healthz {
        access_log off;
        add_header Content-Type text/plain;
        return 200 'ok';
    }

    # Asset & Digital Twin Service Routing
    location /api/v1/assets {
        proxy_pass http://asset_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Simulation & Physics Service Routing
    location /api/v1/simulations {
        proxy_pass http://sim_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # KPI & B2B Service Routing
    location /api/v1/kpi {
        proxy_pass http://kpi_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/v1/procurement {
        proxy_pass http://kpi_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}